// Experimental backend forked from the audited optimizer emitter; oracle guards stay unchanged.
const std = @import("std");
const Silex = @import("silex_optimizer_api");
const Coverage = @import("../OptimizerOracle/LlvmCoverage.zig");
const IrStats = @import("../OptimizerOracle/IrStats.zig");

const Allocator = std.mem.Allocator;
const Ir = Silex.Ir;

pub const Error = Allocator.Error || error{
    InvalidProgram,
    UnsupportedInstruction,
    UnsupportedType,
};

pub fn emit(allocator: Allocator, program: Ir.Program) Error![]u8 {
    return emitWithBoundaries(allocator, program, &.{});
}

pub fn emitWithBoundaries(
    allocator: Allocator,
    program: Ir.Program,
    boundaries: []const Silex.Boundary.Function,
) Error![]u8 {
    const reachable = try IrStats.reachableFunctions(allocator, program);
    defer allocator.free(reachable);
    const boundary_use = try inspectBoundaryUse(allocator, program, boundaries, reachable);
    defer allocator.free(boundary_use.direct_sites_by_function);
    if (boundary_use.unsupported != 0 or boundary_use.indirect_sites != 0) {
        const first = boundary_use.first_unsupported;
        std.debug.print(
            "silex LLVM evaluation: emitter rejected {d} reachable package boundary functions across {d} direct and {d} indirect call sites",
            .{ boundary_use.unsupported, boundary_use.direct_sites, boundary_use.indirect_sites },
        );
        if (first) |index| std.debug.print(
            "; first unsupported reachable boundary is '{s}' from '{s}'",
            .{ boundaries[index].source_name, boundaries[index].provider },
        );
        std.debug.print("\n", .{});
        return error.UnsupportedInstruction;
    }
    const global_use = try inspectGlobalUse(allocator, program, reachable);
    defer allocator.free(global_use.loads);
    defer allocator.free(global_use.stores);
    var unsupported_globals: usize = 0;
    var first_unsupported_global: ?usize = null;
    for (program.globals, 0..) |global, index| {
        if (global_use.loads[index] == 0 and global_use.stores[index] == 0) continue;
        if (global_use.stores[index] != 0 and !global.mutable) return error.InvalidProgram;
        if (supportsStaticGlobal(global)) continue;
        unsupported_globals += 1;
        if (first_unsupported_global == null) first_unsupported_global = index;
    }
    if (unsupported_globals != 0) {
        std.debug.print(
            "silex LLVM evaluation: emitter rejected {d} of {d} reachable global values across {d} loads and {d} stores; first unsupported reachable global is '{s}'\n",
            .{
                unsupported_globals,
                global_use.used,
                global_use.load_sites,
                global_use.store_sites,
                program.globals[first_unsupported_global.?].name,
            },
        );
        return error.UnsupportedInstruction;
    }
    var output: std.ArrayList(u8) = .empty;
    try output.appendSlice(allocator,
        \\; Generated by the explicit Silex LLVM evaluation backend. Experimental.
        \\@.fmt.signed = private constant [6 x i8] c"%lld\0A\00"
        \\@.fmt.signed.inline = private constant [5 x i8] c"%lld\00"
        \\@.fmt.unsigned = private constant [6 x i8] c"%llu\0A\00"
        \\@.fmt.unsigned.inline = private constant [5 x i8] c"%llu\00"
        \\@.fmt.boolean = private constant [4 x i8] c"%s\0A\00"
        \\@.fmt.boolean.inline = private constant [3 x i8] c"%s\00"
        \\@.true = private constant [5 x i8] c"true\00"
        \\@.false = private constant [6 x i8] c"false\00"
        \\
        \\declare i32 @dprintf(i32, ptr, ...)
        \\declare ptr @malloc(i64)
        \\declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1 immarg)
        \\declare void @exit(i32) noreturn
        \\
    );
    try output.appendSlice(allocator, @import("Runtime.zig").text);
    try emitSourceFiles(&output, allocator, program);
    for ([_]u7{ 8, 16, 32, 64 }) |width| {
        for ([_][]const u8{ "sadd", "ssub", "smul", "uadd", "usub", "umul" }) |operation| {
            try appendFmt(
                &output,
                allocator,
                "declare {{ i{d}, i1 }} @llvm.{s}.with.overflow.i{d}(i{d}, i{d})\n",
                .{ width, operation, width, width, width },
            );
        }
        for ([_]struct { suffix: []const u8, type_name: []const u8 }{
            .{ .suffix = "f32", .type_name = "float" },
            .{ .suffix = "f64", .type_name = "double" },
        }) |floating| {
            try appendFmt(
                &output,
                allocator,
                "declare i{d} @llvm.fptosi.sat.i{d}.{s}({s})\n",
                .{ width, width, floating.suffix, floating.type_name },
            );
            try appendFmt(
                &output,
                allocator,
                "declare i{d} @llvm.fptoui.sat.i{d}.{s}({s})\n",
                .{ width, width, floating.suffix, floating.type_name },
            );
        }
    }
    try output.append(allocator, '\n');
    try emitBoundaryDeclarations(
        &output,
        allocator,
        program,
        boundaries,
        boundary_use.direct_sites_by_function,
    );
    try emitGlobalDeclarations(&output, allocator, program, global_use);
    for (program.structures, 0..) |structure, structure_index| {
        if (structure.collection != null) {
            try appendFmt(&output, allocator, "%sx.type.{d} = type {{ ptr, i64 }}\n", .{structure_index});
            continue;
        }
        if (structure.is_class or structure.is_static or structure.is_protocol)
            return error.UnsupportedType;
        try appendFmt(&output, allocator, "%sx.type.{d} = type {{ ", .{structure_index});
        for (structure.fields, 0..) |field, field_index| {
            if (field_index != 0) try output.appendSlice(allocator, ", ");
            try output.appendSlice(allocator, try llvmType(allocator, program, field.type));
        }
        try output.appendSlice(allocator, " }\n");
    }
    if (program.structures.len != 0) try output.append(allocator, '\n');

    var main_function: ?usize = null;
    for (program.functions, 0..) |function, function_id| {
        if (std.mem.eql(u8, function.name, "main")) {
            if (main_function != null) return error.InvalidProgram;
            main_function = function_id;
        }
        if (!reachable[function_id]) continue;
        var emitter: FunctionEmitter = .{
            .allocator = allocator,
            .output = &output,
            .program = program,
            .boundaries = boundaries,
            .function = try @import("../OptimizerOracle/LlvmValues.zig").lower(allocator, function),
            .function_id = function_id,
        };
        emitter.emit() catch |err| {
            std.debug.print(
                "silex LLVM evaluation: emitter rejected function '{s}': {t}\n",
                .{ function.name, err },
            );
            return err;
        };
    }
    const main_id = main_function orelse return error.InvalidProgram;
    const main = program.functions[main_id];
    if (main.parameter_types.len != 0 or main.return_type != .void) return error.UnsupportedType;
    try appendFmt(&output, allocator,
        \\define i32 @main() {{
        \\entry:
        \\  call fastcc void @sx_{d}()
        \\  call fastcc void @sx_finish()
        \\  ret i32 0
        \\}}
        \\
    , .{main_id});
    return output.toOwnedSlice(allocator);
}

pub fn closureReport(
    allocator: Allocator,
    program: Ir.Program,
    boundaries: []const Silex.Boundary.Function,
) Error![]u8 {
    const reachable = try IrStats.reachableFunctions(allocator, program);
    defer allocator.free(reachable);
    const boundary_use = try inspectBoundaryUse(allocator, program, boundaries, reachable);
    defer allocator.free(boundary_use.direct_sites_by_function);
    const global_use = try inspectGlobalUse(allocator, program, reachable);
    defer allocator.free(global_use.loads);
    defer allocator.free(global_use.stores);
    const instruction_use = inspectInstructionUse(program, reachable);
    const instruction_coverage = try instructionCoverageEntries(allocator, instruction_use);
    defer allocator.free(instruction_coverage);

    var reachable_function_count: usize = 0;
    for (reachable) |is_reachable| if (is_reachable) {
        reachable_function_count += 1;
    };
    var direct_function_count: usize = 0;
    for (boundary_use.direct_sites_by_function) |sites| if (sites != 0) {
        direct_function_count += 1;
    };
    const entries = try allocator.alloc(BoundaryInventoryEntry, direct_function_count);
    var entry_index: usize = 0;
    for (boundaries, 0..) |boundary, index| {
        const sites = boundary_use.direct_sites_by_function[index];
        if (sites == 0) continue;
        entries[entry_index] = .{
            .index = index,
            .owner = boundary.owner,
            .name = boundary.name,
            .provider = boundary.provider,
            .source_name = boundary.source_name,
            .parameters = boundary.parameters,
            .return_type = boundary.return_type,
            .direct_sites = sites,
            .supported_by_prototype = supportsDirectBoundary(boundary),
        };
        entry_index += 1;
    }
    const globals = try allocator.alloc(GlobalInventoryEntry, global_use.used);
    var global_entry_index: usize = 0;
    for (program.globals, 0..) |global, index| {
        if (global_use.loads[index] == 0 and global_use.stores[index] == 0) continue;
        globals[global_entry_index] = .{
            .index = index,
            .name = global.name,
            .type = global.type,
            .type_name = try reportTypeName(allocator, program, global.type),
            .mutable = global.mutable,
            .runtime_initialized = global.runtime_initialized,
            .bits = global.bits,
            .extra_bits = global.extra_bits,
            .loads = global_use.loads[index],
            .stores = global_use.stores[index],
        };
        global_entry_index += 1;
    }
    return std.json.Stringify.valueAlloc(allocator, .{
        .boundary_table_size = boundaries.len,
        .reachable_functions = reachable_function_count,
        .reachable_direct_boundary_functions = direct_function_count,
        .direct_call_sites = boundary_use.direct_sites,
        .indirect_call_sites = boundary_use.indirect_sites,
        .functions = entries,
        .global_table_size = program.globals.len,
        .reachable_global_values = global_use.used,
        .global_load_sites = global_use.load_sites,
        .global_store_sites = global_use.store_sites,
        .globals = globals,
        .instruction_sites = instruction_use.sites_total,
        .conditionally_supported_instruction_sites = instruction_use.conditional_sites,
        .abstract_lifetime_instruction_sites = instruction_use.abstract_lifetime_sites,
        .unsupported_instruction_sites = instruction_use.unsupported_sites,
        .unsupported_instruction_kinds = instruction_use.unsupported_kinds,
        .functions_with_unsupported_instructions = instruction_use.functions_with_unsupported,
        .instruction_coverage = instruction_coverage,
    }, .{ .whitespace = .indent_2 });
}

const BoundaryInventoryEntry = struct {
    index: usize,
    owner: usize,
    name: []const u8,
    provider: []const u8,
    source_name: []const u8,
    parameters: []const Ir.Type,
    return_type: Ir.Type,
    direct_sites: usize,
    supported_by_prototype: bool,
};

const GlobalInventoryEntry = struct {
    index: usize,
    name: []const u8,
    type: Ir.Type,
    type_name: []const u8,
    mutable: bool,
    runtime_initialized: bool,
    bits: u64,
    extra_bits: []const u64,
    loads: usize,
    stores: usize,
};

const InstructionTag = std.meta.Tag(Ir.Instruction);
const instruction_tag_count = @typeInfo(InstructionTag).@"enum".fields.len;

const InstructionUse = struct {
    sites: [instruction_tag_count]usize = [_]usize{0} ** instruction_tag_count,
    functions: [instruction_tag_count]usize = [_]usize{0} ** instruction_tag_count,
    sites_total: usize = 0,
    conditional_sites: usize = 0,
    abstract_lifetime_sites: usize = 0,
    unsupported_sites: usize = 0,
    unsupported_kinds: usize = 0,
    functions_with_unsupported: usize = 0,
};

const InstructionCoverageEntry = struct {
    name: []const u8,
    support: []const u8,
    sites: usize,
    functions: usize,
};

fn inspectInstructionUse(program: Ir.Program, reachable: []const bool) InstructionUse {
    var result: InstructionUse = .{};
    for (program.functions, 0..) |function, function_index| {
        if (!reachable[function_index]) continue;
        var seen = [_]bool{false} ** instruction_tag_count;
        var function_has_unsupported = false;
        for (function.blocks) |block| for (block.instructions) |instruction| {
            const tag = std.meta.activeTag(instruction);
            const index: usize = @intFromEnum(tag);
            result.sites[index] += 1;
            result.sites_total += 1;
            if (!seen[index]) {
                seen[index] = true;
                result.functions[index] += 1;
            }
            switch (Coverage.classify(tag)) {
                .conditional => result.conditional_sites += 1,
                .abstract_lifetime => result.abstract_lifetime_sites += 1,
                .unsupported => {
                    result.unsupported_sites += 1;
                    function_has_unsupported = true;
                },
            }
        };
        if (function_has_unsupported) result.functions_with_unsupported += 1;
    }
    inline for (@typeInfo(InstructionTag).@"enum".fields) |field| {
        const tag: InstructionTag = @enumFromInt(field.value);
        if (result.sites[field.value] != 0 and Coverage.classify(tag) == .unsupported)
            result.unsupported_kinds += 1;
    }
    return result;
}

fn instructionCoverageEntries(allocator: Allocator, use: InstructionUse) Allocator.Error![]InstructionCoverageEntry {
    var used_kinds: usize = 0;
    inline for (@typeInfo(InstructionTag).@"enum".fields) |field| {
        if (use.sites[field.value] != 0) used_kinds += 1;
    }
    const entries = try allocator.alloc(InstructionCoverageEntry, used_kinds);
    var entry_index: usize = 0;
    inline for (@typeInfo(InstructionTag).@"enum".fields) |field| {
        if (use.sites[field.value] != 0) {
            const tag: InstructionTag = @enumFromInt(field.value);
            entries[entry_index] = .{
                .name = field.name,
                .support = @tagName(Coverage.classify(tag)),
                .sites = use.sites[field.value],
                .functions = use.functions[field.value],
            };
            entry_index += 1;
        }
    }
    return entries;
}

fn reportTypeName(allocator: Allocator, program: Ir.Program, type_value: Ir.Type) Error![]const u8 {
    if (type_value.optionalChild()) |child| {
        return std.fmt.allocPrint(allocator, "{s}?", .{try reportTypeName(allocator, program, child)});
    }
    if (type_value.structureIndex()) |index| {
        if (index >= program.structures.len) return error.InvalidProgram;
        return std.fmt.allocPrint(allocator, "@{s}", .{program.structures[index].name});
    }
    if (type_value.functionIndex()) |index| {
        if (index >= program.function_types.len) return error.InvalidProgram;
        return std.fmt.allocPrint(allocator, "func#{d}", .{index});
    }
    return switch (type_value) {
        .void,
        .bool,
        .int8,
        .uint8,
        .int16,
        .uint16,
        .int32,
        .uint32,
        .int,
        .uint,
        .float32,
        .float64,
        .str,
        .address,
        => @tagName(type_value),
        else => std.fmt.allocPrint(allocator, "type#{d}", .{@intFromEnum(type_value)}),
    };
}

const BoundaryUse = struct {
    direct_sites_by_function: []usize,
    direct_sites: usize = 0,
    indirect_sites: usize = 0,
    unsupported: usize = 0,
    first_unsupported: ?usize = null,
};

fn inspectBoundaryUse(
    allocator: Allocator,
    program: Ir.Program,
    boundaries: []const Silex.Boundary.Function,
    reachable: []const bool,
) Error!BoundaryUse {
    if (reachable.len != program.functions.len) return error.InvalidProgram;
    var result: BoundaryUse = .{ .direct_sites_by_function = try allocator.alloc(usize, boundaries.len) };
    @memset(result.direct_sites_by_function, 0);
    errdefer allocator.free(result.direct_sites_by_function);
    for (program.functions, 0..) |function, function_index| {
        if (!reachable[function_index]) continue;
        for (function.blocks) |block| for (block.instructions) |instruction| switch (instruction) {
            .boundary_call => |call| {
                if (call.function >= boundaries.len) return error.InvalidProgram;
                result.direct_sites += 1;
                result.direct_sites_by_function[call.function] += 1;
            },
            .boundary_indirect_call => result.indirect_sites += 1,
            else => {},
        };
    }
    for (result.direct_sites_by_function, 0..) |sites, index| {
        if (sites == 0 or supportsDirectBoundary(boundaries[index])) continue;
        result.unsupported += 1;
        if (result.first_unsupported == null) result.first_unsupported = index;
    }
    return result;
}

const GlobalUse = struct {
    loads: []usize,
    stores: []usize,
    used: usize = 0,
    load_sites: usize = 0,
    store_sites: usize = 0,
};

fn inspectGlobalUse(
    allocator: Allocator,
    program: Ir.Program,
    reachable: []const bool,
) Error!GlobalUse {
    if (reachable.len != program.functions.len) return error.InvalidProgram;
    const loads = try allocator.alloc(usize, program.globals.len);
    errdefer allocator.free(loads);
    const stores = try allocator.alloc(usize, program.globals.len);
    errdefer allocator.free(stores);
    var result: GlobalUse = .{
        .loads = loads,
        .stores = stores,
    };
    @memset(result.loads, 0);
    @memset(result.stores, 0);
    for (program.functions, 0..) |function, function_index| {
        if (!reachable[function_index]) continue;
        for (function.blocks) |block| for (block.instructions) |instruction| switch (instruction) {
            .global_load => |load| {
                if (load.global >= program.globals.len) return error.InvalidProgram;
                result.loads[load.global] += 1;
                result.load_sites += 1;
            },
            .global_store => |store| {
                if (store.global >= program.globals.len) return error.InvalidProgram;
                result.stores[store.global] += 1;
                result.store_sites += 1;
            },
            else => {},
        };
    }
    for (result.loads, result.stores) |load_count, store_count| if (load_count != 0 or store_count != 0) {
        result.used += 1;
    };
    return result;
}

fn supportsStaticGlobal(global: Ir.Global) bool {
    if (global.runtime_initialized or global.extra_bits.len != 0) return false;
    return global.type.isInteger();
}

fn emitGlobalDeclarations(
    output: *std.ArrayList(u8),
    allocator: Allocator,
    program: Ir.Program,
    use: GlobalUse,
) Error!void {
    var emitted = false;
    for (program.globals, 0..) |global, index| {
        if (use.loads[index] == 0 and use.stores[index] == 0) continue;
        if (!supportsStaticGlobal(global)) return error.UnsupportedType;
        try appendFmt(output, allocator, "@sx.global.{d} = internal {s} {s} {d}\n", .{
            index,
            if (global.mutable) "global" else "constant",
            try llvmType(allocator, program, global.type),
            normalize(global.bits, global.type),
        });
        emitted = true;
    }
    if (emitted) try output.append(allocator, '\n');
}

const FunctionEmitter = struct {
    allocator: Allocator,
    output: *std.ArrayList(u8),
    program: Ir.Program,
    boundaries: []const Silex.Boundary.Function,
    function: Ir.Function,
    function_id: usize,
    temporary: usize = 0,

    fn emit(self: *FunctionEmitter) Error!void {
        if (self.function.capture_types.len != 0) return error.UnsupportedInstruction;
        try self.write("define internal fastcc {s} @sx_{d}(", .{ try llvmType(self.allocator, self.program, self.function.return_type), self.function_id });
        for (self.function.parameter_types, 0..) |type_value, index| {
            if (index != 0) try self.output.appendSlice(self.allocator, ", ");
            try self.write("{s} %v{d}", .{ try llvmType(self.allocator, self.program, type_value), index });
        }
        try self.output.appendSlice(self.allocator, ") {\n");
        for (self.function.blocks, 0..) |block, block_id| {
            try self.write("b{d}:\n", .{block_id});
            if (block_id == 0) {
                for (self.function.local_types, 0..) |type_value, local| {
                    try self.write("  %local{d} = alloca {s}\n", .{ local, try llvmType(self.allocator, self.program, type_value) });
                }
            }
            for (block.instructions, 0..) |instruction, instruction_index| {
                self.emitInstruction(block_id, instruction) catch |err| {
                    std.debug.print(
                        "silex LLVM evaluation: emitter rejected function '{s}', block {d}, instruction {d} ({s}): {t}\n",
                        .{ self.function.name, block_id, instruction_index, @tagName(instruction), err },
                    );
                    return err;
                };
            }
            try self.emitTerminator(block.terminator);
        }
        try self.output.appendSlice(self.allocator,
            \\trap:
            \\  call void @exit(i32 1)
            \\  unreachable
            \\}
            \\
        );
    }

    fn emitInstruction(self: *FunctionEmitter, block_id: usize, instruction: Ir.Instruction) Error!void {
        if (Coverage.classify(std.meta.activeTag(instruction)) == .unsupported)
            return error.UnsupportedInstruction;
        switch (instruction) {
            .constant_int => |value| {
                const type_value = try self.valueType(value.result);
                const bits = normalize(value.bits, type_value);
                try self.write("  %v{d} = add {s} 0, {d}\n", .{ value.result, try llvmType(self.allocator, self.program, type_value), bits });
            },
            .constant_bool => |value| try self.write(
                "  %v{d} = xor i1 false, {s}\n",
                .{ value.result, if (value.value) "true" else "false" },
            ),
            .constant_float32 => |value| try self.write(
                "  %v{d} = bitcast i32 {d} to float\n",
                .{ value.result, value.bits },
            ),
            .constant_float64 => |value| try self.write(
                "  %v{d} = bitcast i64 {d} to double\n",
                .{ value.result, value.bits },
            ),
            .copy => |value| try self.copyValue(value.result, value.operand),
            .deep_copy => |value| try self.emitDeepCopy(value.result, value.operand),
            .structure_init => |value| try self.emitStructureInit(value),
            .list_init => |value| try self.emitListInit(value),
            .list_retain => |value| try self.emitListResource(value, "sx_retain"),
            .list_drop => |value| try self.emitListResource(value, "sx_drop"),
            .field_load => |value| try self.emitFieldLoad(value),
            .collection_load => |value| try self.emitCollectionLoad(block_id, value),
            .collection_reference => |value| try self.emitCollectionReference(block_id, value),
            .collection_replace => |value| try self.emitCollectionReplace(block_id, value),
            .collection_count => |value| try self.emitCollectionCount(value),
            .collection_view => |value| try self.emitCollectionView(block_id, value),
            .local_load => |value| try self.write(
                "  %v{d} = load {s}, ptr %local{d}\n",
                .{ value.result, try llvmType(self.allocator, self.program, try self.valueType(value.result)), value.local },
            ),
            .local_store => |value| try self.write(
                "  store {s} %v{d}, ptr %local{d}\n",
                .{ try llvmType(self.allocator, self.program, try self.valueType(value.operand)), value.operand, value.local },
            ),
            .global_load => |value| try self.emitGlobalLoad(value),
            .global_store => |value| try self.emitGlobalStore(value),
            .local_address => |value| try self.emitLocalAddress(value),
            .reference_load => |value| try self.emitReferenceLoad(value),
            .reference_store => |value| try self.emitReferenceStore(value),
            .reference_field => |value| try self.emitReferenceField(value),
            .unary => |value| try self.emitNegate(block_id, value),
            .binary => |value| try self.emitBinary(block_id, value),
            .convert => |value| try self.emitConvert(block_id, value),
            .call => |value| try self.emitCall(value),
            .boundary_call => |value| try self.emitBoundaryCall(value),
            .print => |value| try self.emitPrint(value),
            else => return error.UnsupportedInstruction,
        }
    }

    fn emitGlobalLoad(self: *FunctionEmitter, value: Ir.Instruction.GlobalLoad) Error!void {
        if (value.global >= self.program.globals.len) return error.InvalidProgram;
        const global = self.program.globals[value.global];
        if (!supportsStaticGlobal(global) or try self.valueType(value.result) != global.type)
            return error.InvalidProgram;
        try self.write("  %v{d} = load {s}, ptr @sx.global.{d}\n", .{
            value.result,
            try llvmType(self.allocator, self.program, global.type),
            value.global,
        });
    }

    fn emitGlobalStore(self: *FunctionEmitter, value: Ir.Instruction.GlobalStore) Error!void {
        if (value.global >= self.program.globals.len) return error.InvalidProgram;
        const global = self.program.globals[value.global];
        if (!global.mutable or !supportsStaticGlobal(global) or try self.valueType(value.operand) != global.type)
            return error.InvalidProgram;
        try self.write("  store {s} %v{d}, ptr @sx.global.{d}\n", .{
            try llvmType(self.allocator, self.program, global.type),
            value.operand,
            value.global,
        });
    }

    fn emitListResource(self: *FunctionEmitter, value: Ir.Instruction.ListResource, comptime operation: []const u8) Error!void {
        const type_value = try self.valueType(value.operand);
        const collection = try self.collectionInfo(type_value);
        if (value.ownership != .root or collection.view or !plainValue(self.program, collection.element, 0))
            return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        try self.write("  %t{d}.owned = extractvalue {s} %v{d}, 0\n", .{ serial, try llvmType(self.allocator, self.program, type_value), value.operand });
        try self.write("  call fastcc void @{s}(ptr %t{d}.owned)\n", .{ operation, serial });
    }

    fn emitBoundsFailure(self: *FunctionEmitter, block_id: usize, serial: usize, index: Ir.ValueId, position: @TypeOf(@as(Ir.Instruction.CollectionLoad, undefined).position)) Error!void {
        if (position.file >= self.program.files.len) return error.InvalidProgram;
        try self.write("  br i1 %t{d}.index.invalid, label %b{d}.fail{d}, label %b{d}.cont{d}\n", .{ serial, block_id, serial, block_id, serial });
        try self.write("b{d}.fail{d}:\n", .{ block_id, serial });
        try self.write("  call fastcc void @sx_bounds(ptr @sx.file.{d}, i64 {d}, i64 {d}, i64 %v{d}, i64 %t{d}.count)\n", .{ position.file, position.line, position.column, index, serial });
        try self.write("  unreachable\nb{d}.cont{d}:\n", .{ block_id, serial });
    }

    fn emitConversionFailure(self: *FunctionEmitter, block_id: usize, serial: usize, value: Ir.Instruction.Convert, exact: bool) Error!void {
        if (value.position.file >= self.program.files.len) return error.InvalidProgram;
        if (exact) {
            try self.write("  br i1 %t{d}.exact, label %b{d}.cont{d}, label %b{d}.fail{d}\n", .{ serial, block_id, serial, block_id, serial });
        } else {
            try self.write("  br i1 %t{d}.invalid, label %b{d}.fail{d}, label %b{d}.cont{d}\n", .{ serial, block_id, serial, block_id, serial });
        }
        try self.write("b{d}.fail{d}:\n", .{ block_id, serial });
        try self.write("  call fastcc void @sx_conversion(ptr @sx.file.{d}, i64 {d}, i64 {d})\n", .{ value.position.file, value.position.line, value.position.column });
        try self.write("  unreachable\nb{d}.cont{d}:\n", .{ block_id, serial });
    }

    fn copyValue(self: *FunctionEmitter, result: Ir.ValueId, operand: Ir.ValueId) Error!void {
        const type_name = try llvmType(self.allocator, self.program, try self.valueType(result));
        try self.write("  %v{d} = select i1 true, {s} %v{d}, {s} %v{d}\n", .{
            result,
            type_name,
            operand,
            type_name,
            operand,
        });
    }

    fn emitDeepCopy(self: *FunctionEmitter, result: Ir.ValueId, operand: Ir.ValueId) Error!void {
        const type_value = try self.valueType(result);
        if (type_value != try self.valueType(operand)) return error.InvalidProgram;
        const collection = self.collectionInfo(type_value) catch return self.copyValue(result, operand);
        if (collection.view or !plainValue(self.program, collection.element, 0))
            return error.UnsupportedType;

        const serial = self.nextTemporary();
        const type_name = try llvmType(self.allocator, self.program, type_value);
        try self.write("  %t{d}.source = extractvalue {s} %v{d}, 0\n", .{ serial, type_name, operand });
        try self.write("  %t{d}.count = extractvalue {s} %v{d}, 1\n", .{ serial, type_name, operand });
        try self.emitCollectionBytes(serial, collection.element);
        try self.write("  %t{d}.storage = call fastcc ptr @sx_alloc(i64 %t{d}.bytes)\n", .{ serial, serial });
        try self.write(
            "  call void @llvm.memcpy.p0.p0.i64(ptr %t{d}.storage, ptr %t{d}.source, i64 %t{d}.bytes, i1 false)\n",
            .{ serial, serial, serial },
        );
        try self.write("  %t{d}.collection = insertvalue {s} poison, ptr %t{d}.storage, 0\n", .{
            serial,
            type_name,
            serial,
        });
        try self.write("  %v{d} = insertvalue {s} %t{d}.collection, i64 %t{d}.count, 1\n", .{
            result,
            type_name,
            serial,
            serial,
        });
    }

    fn emitStructureInit(self: *FunctionEmitter, value: Ir.Instruction.StructureInit) Error!void {
        if (value.structure >= self.program.structures.len) return error.InvalidProgram;
        const structure = self.program.structures[value.structure];
        if (value.fields.len != structure.fields.len or try self.valueType(value.result) != Ir.Type.structure(value.structure))
            return error.InvalidProgram;
        const type_name = try llvmType(self.allocator, self.program, Ir.Type.structure(value.structure));
        if (value.fields.len == 0) {
            try self.write("  %v{d} = freeze {s} poison\n", .{ value.result, type_name });
            return;
        }
        const serial = self.nextTemporary();
        for (value.fields, 0..) |field, field_index| {
            if (try self.valueType(field) != structure.fields[field_index].type) return error.InvalidProgram;
            if (field_index + 1 == value.fields.len)
                try self.write("  %v{d} = insertvalue {s} {s}, {s} %v{d}, {d}\n", .{
                    value.result,
                    type_name,
                    if (field_index == 0) "poison" else try std.fmt.allocPrint(self.allocator, "%t{d}.aggregate{d}", .{ serial, field_index - 1 }),
                    try llvmType(self.allocator, self.program, structure.fields[field_index].type),
                    field,
                    field_index,
                })
            else
                try self.write("  %t{d}.aggregate{d} = insertvalue {s} {s}, {s} %v{d}, {d}\n", .{
                    serial,
                    field_index,
                    type_name,
                    if (field_index == 0) "poison" else try std.fmt.allocPrint(self.allocator, "%t{d}.aggregate{d}", .{ serial, field_index - 1 }),
                    try llvmType(self.allocator, self.program, structure.fields[field_index].type),
                    field,
                    field_index,
                });
        }
    }

    fn emitFieldLoad(self: *FunctionEmitter, value: Ir.Instruction.FieldLoad) Error!void {
        const base_type = try self.valueType(value.base);
        const structure_index = base_type.structureIndex() orelse return error.InvalidProgram;
        if (structure_index >= self.program.structures.len or value.field >= self.program.structures[structure_index].fields.len)
            return error.InvalidProgram;
        if (try self.valueType(value.result) != self.program.structures[structure_index].fields[value.field].type)
            return error.InvalidProgram;
        try self.write("  %v{d} = extractvalue {s} %v{d}, {d}\n", .{
            value.result,
            try llvmType(self.allocator, self.program, base_type),
            value.base,
            value.field,
        });
    }

    fn emitListInit(self: *FunctionEmitter, value: Ir.Instruction.ListInit) Error!void {
        const type_value = try self.valueType(value.result);
        const collection = try self.collectionInfo(type_value);
        if (!plainValue(self.program, collection.element, 0)) return error.UnsupportedType;
        const element_name = try llvmType(self.allocator, self.program, collection.element);
        const type_name = try llvmType(self.allocator, self.program, type_value);
        const serial = self.nextTemporary();
        try self.write("  %t{d}.count = add i64 0, {d}\n", .{ serial, value.values.len });
        try self.emitCollectionBytes(serial, collection.element);
        // A literal can escape its creating function. Its allocation is owned
        // by the retains/drops present in the composed Silex IR.
        try self.write("  %t{d}.storage = call fastcc ptr @sx_alloc(i64 %t{d}.bytes)\n", .{ serial, serial });
        for (value.values, 0..) |item, index| {
            if (try self.valueType(item) != collection.element) return error.InvalidProgram;
            try self.write("  %t{d}.item{d} = getelementptr {s}, ptr %t{d}.storage, i64 {d}\n", .{
                serial, index, element_name, serial, index,
            });
            try self.write("  store {s} %v{d}, ptr %t{d}.item{d}\n", .{ element_name, item, serial, index });
        }
        try self.write("  %t{d}.collection = insertvalue {s} poison, ptr %t{d}.storage, 0\n", .{
            serial,
            type_name,
            serial,
        });
        try self.write("  %v{d} = insertvalue {s} %t{d}.collection, i64 {d}, 1\n", .{
            value.result,
            type_name,
            serial,
            value.values.len,
        });
    }

    fn emitCollectionCount(self: *FunctionEmitter, value: Ir.Instruction.CollectionCount) Error!void {
        const collection_type = try self.valueType(value.collection);
        _ = try self.collectionInfo(collection_type);
        if (try self.valueType(value.result) != .int) return error.InvalidProgram;
        try self.write("  %v{d} = extractvalue {s} %v{d}, 1\n", .{
            value.result,
            try llvmType(self.allocator, self.program, collection_type),
            value.collection,
        });
    }

    fn emitCollectionLoad(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.CollectionLoad) Error!void {
        const collection_type = try self.valueType(value.collection);
        const collection = try self.collectionInfo(collection_type);
        if (try self.valueType(value.index) != .int or try self.valueType(value.result) != collection.element)
            return error.InvalidProgram;
        const serial = self.nextTemporary();
        const type_name = try llvmType(self.allocator, self.program, collection_type);
        const element_name = try llvmType(self.allocator, self.program, collection.element);
        try self.write("  %t{d}.data = extractvalue {s} %v{d}, 0\n", .{ serial, type_name, value.collection });
        try self.write("  %t{d}.count = extractvalue {s} %v{d}, 1\n", .{ serial, type_name, value.collection });
        try self.emitNormalizedIndex(serial, "index", value.index);
        if (value.checked) {
            try self.write("  %t{d}.index.low = icmp slt i64 %t{d}.index, 0\n", .{ serial, serial });
            try self.write("  %t{d}.index.high = icmp sge i64 %t{d}.index, %t{d}.count\n", .{ serial, serial, serial });
            try self.write("  %t{d}.index.invalid = or i1 %t{d}.index.low, %t{d}.index.high\n", .{ serial, serial, serial });
            try self.emitBoundsFailure(block_id, serial, value.index, value.position);
        }
        try self.write("  %t{d}.element = getelementptr {s}, ptr %t{d}.data, i64 %t{d}.index\n", .{
            serial,
            element_name,
            serial,
            serial,
        });
        try self.write("  %v{d} = load {s}, ptr %t{d}.element\n", .{ value.result, element_name, serial });
    }

    fn emitCollectionReference(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.CollectionReference) Error!void {
        const collection_type = try self.valueType(value.collection);
        const collection = try self.collectionInfo(collection_type);
        // Owning references can require detaching shared storage. Only borrowed
        // views are modeled here; never silently turn copy-on-write into aliasing.
        if (!collection.view or value.ownership != .root or !plainValue(self.program, collection.element, 0))
            return error.UnsupportedInstruction;
        if (try self.valueType(value.index) != .int or try self.valueType(value.result) != .address)
            return error.InvalidProgram;
        const serial = self.nextTemporary();
        const type_name = try llvmType(self.allocator, self.program, collection_type);
        if (value.reference) |reference| {
            if (try self.valueType(reference) != .address) return error.InvalidProgram;
            try self.write("  %t{d}.source = load {s}, ptr %v{d}\n", .{ serial, type_name, reference });
            try self.write("  %t{d}.data = extractvalue {s} %t{d}.source, 0\n", .{ serial, type_name, serial });
            try self.write("  %t{d}.count = extractvalue {s} %t{d}.source, 1\n", .{ serial, type_name, serial });
        } else {
            try self.write("  %t{d}.data = extractvalue {s} %v{d}, 0\n", .{ serial, type_name, value.collection });
            try self.write("  %t{d}.count = extractvalue {s} %v{d}, 1\n", .{ serial, type_name, value.collection });
        }
        try self.emitNormalizedIndex(serial, "index", value.index);
        if (value.checked) {
            try self.write("  %t{d}.index.low = icmp slt i64 %t{d}.index, 0\n", .{ serial, serial });
            try self.write("  %t{d}.index.high = icmp sge i64 %t{d}.index, %t{d}.count\n", .{ serial, serial, serial });
            try self.write("  %t{d}.index.invalid = or i1 %t{d}.index.low, %t{d}.index.high\n", .{ serial, serial, serial });
            try self.emitBoundsFailure(block_id, serial, value.index, value.position);
        }
        try self.write("  %v{d} = getelementptr {s}, ptr %t{d}.data, i64 %t{d}.index\n", .{
            value.result, try llvmType(self.allocator, self.program, collection.element), serial, serial,
        });
    }

    fn emitCollectionBytes(self: *FunctionEmitter, serial: usize, element: Ir.Type) Error!void {
        // Let LLVM compute its own aggregate padding; Silex's storage slots
        // are not the oracle's layout and cannot be used as a byte stride.
        try self.write("  %t{d}.end = getelementptr {s}, ptr null, i64 %t{d}.count\n", .{
            serial, try llvmType(self.allocator, self.program, element), serial,
        });
        try self.write("  %t{d}.bytes = ptrtoint ptr %t{d}.end to i64\n", .{ serial, serial });
    }

    fn emitCollectionReplace(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.CollectionReplace) Error!void {
        const collection_type = try self.valueType(value.collection);
        const collection = try self.collectionInfo(collection_type);
        if (value.ownership != .root or
            try self.valueType(value.result) != collection_type or
            try self.valueType(value.index) != .int or
            try self.valueType(value.replacement) != collection.element or
            !plainValue(self.program, collection.element, 0))
        {
            return error.UnsupportedInstruction;
        }
        const serial = self.nextTemporary();
        const type_name = try llvmType(self.allocator, self.program, collection_type);
        const element_name = try llvmType(self.allocator, self.program, collection.element);
        try self.write("  %t{d}.data = extractvalue {s} %v{d}, 0\n", .{ serial, type_name, value.collection });
        try self.write("  %t{d}.count = extractvalue {s} %v{d}, 1\n", .{ serial, type_name, value.collection });
        try self.emitNormalizedIndex(serial, "index", value.index);
        if (value.checked) {
            try self.write("  %t{d}.index.low = icmp slt i64 %t{d}.index, 0\n", .{ serial, serial });
            try self.write("  %t{d}.index.high = icmp sge i64 %t{d}.index, %t{d}.count\n", .{ serial, serial, serial });
            try self.write("  %t{d}.index.invalid = or i1 %t{d}.index.low, %t{d}.index.high\n", .{ serial, serial, serial });
            try self.emitBoundsFailure(block_id, serial, value.index, value.position);
        }
        if (!collection.view) {
            try self.emitCollectionBytes(serial, collection.element);
            try self.write("  %t{d}.copy = call fastcc ptr @sx_alloc(i64 %t{d}.bytes)\n", .{ serial, serial });
            try self.write(
                "  call void @llvm.memcpy.p0.p0.i64(ptr %t{d}.copy, ptr %t{d}.data, i64 %t{d}.bytes, i1 false)\n",
                .{ serial, serial, serial },
            );
            // collection_replace transfers the consumed owning root to its result.
            // Cloning the payload must release that root, including when it was shared.
            try self.write("  call fastcc void @sx_drop(ptr %t{d}.data)\n", .{serial});
        }
        try self.write("  %t{d}.element = getelementptr {s}, ptr %t{d}.{s}, i64 %t{d}.index\n", .{
            serial,
            element_name,
            serial,
            if (collection.view) "data" else "copy",
            serial,
        });
        try self.write("  store {s} %v{d}, ptr %t{d}.element\n", .{ element_name, value.replacement, serial });
        if (collection.view) {
            try self.copyValue(value.result, value.collection);
        } else {
            try self.write("  %t{d}.updated = insertvalue {s} poison, ptr %t{d}.copy, 0\n", .{
                serial,
                type_name,
                serial,
            });
            try self.write("  %v{d} = insertvalue {s} %t{d}.updated, i64 %t{d}.count, 1\n", .{
                value.result,
                type_name,
                serial,
                serial,
            });
        }
    }

    fn emitCollectionView(self: *FunctionEmitter, _: usize, value: Ir.Instruction.CollectionSlice) Error!void {
        const source_type = try self.valueType(value.collection);
        const result_type = try self.valueType(value.result);
        const source = try self.collectionInfo(source_type);
        const result = try self.collectionInfo(result_type);
        if (value.reference != null and !source.view) return error.UnsupportedInstruction;
        if (source.element != result.element or !result.view or
            try self.valueType(value.start) != .int or try self.valueType(value.end) != .int)
            return error.InvalidProgram;
        const serial = self.nextTemporary();
        const source_name = try llvmType(self.allocator, self.program, source_type);
        const result_name = try llvmType(self.allocator, self.program, result_type);
        const element_name = try llvmType(self.allocator, self.program, source.element);
        if (value.reference) |reference| {
            if (try self.valueType(reference) != .address) return error.InvalidProgram;
            try self.write("  %t{d}.source = load {s}, ptr %v{d}\n", .{ serial, source_name, reference });
            try self.write("  %t{d}.data = extractvalue {s} %t{d}.source, 0\n", .{ serial, source_name, serial });
            try self.write("  %t{d}.count = extractvalue {s} %t{d}.source, 1\n", .{ serial, source_name, serial });
        } else {
            try self.write("  %t{d}.data = extractvalue {s} %v{d}, 0\n", .{ serial, source_name, value.collection });
            try self.write("  %t{d}.count = extractvalue {s} %v{d}, 1\n", .{ serial, source_name, value.collection });
        }
        try self.emitClampedSliceBound(serial, "start", value.start);
        try self.emitClampedSliceBound(serial, "end", value.end);
        try self.write("  %t{d}.view.data = getelementptr {s}, ptr %t{d}.data, i64 %t{d}.start.clamped\n", .{
            serial, element_name, serial, serial,
        });
        try self.write("  %t{d}.view.difference = sub i64 %t{d}.end.clamped, %t{d}.start.clamped\n", .{ serial, serial, serial });
        try self.write("  %t{d}.view.nonempty = icmp sgt i64 %t{d}.view.difference, 0\n", .{ serial, serial });
        try self.write("  %t{d}.view.count = select i1 %t{d}.view.nonempty, i64 %t{d}.view.difference, i64 0\n", .{ serial, serial, serial });
        try self.write("  %t{d}.view = insertvalue {s} poison, ptr %t{d}.view.data, 0\n", .{
            serial,
            result_name,
            serial,
        });
        try self.write("  %v{d} = insertvalue {s} %t{d}.view, i64 %t{d}.view.count, 1\n", .{
            value.result,
            result_name,
            serial,
            serial,
        });
    }

    fn emitClampedSliceBound(self: *FunctionEmitter, serial: usize, comptime name: []const u8, value: Ir.ValueId) Error!void {
        try self.emitNormalizedIndex(serial, name, value);
        try self.write("  %t{d}.{s}.low = icmp slt i64 %t{d}.{s}, 0\n", .{ serial, name, serial, name });
        try self.write("  %t{d}.{s}.nonnegative = select i1 %t{d}.{s}.low, i64 0, i64 %t{d}.{s}\n", .{ serial, name, serial, name, serial, name });
        try self.write("  %t{d}.{s}.high = icmp sgt i64 %t{d}.{s}.nonnegative, %t{d}.count\n", .{ serial, name, serial, name, serial });
        try self.write("  %t{d}.{s}.clamped = select i1 %t{d}.{s}.high, i64 %t{d}.count, i64 %t{d}.{s}.nonnegative\n", .{ serial, name, serial, name, serial, serial, name });
    }

    fn emitNormalizedIndex(self: *FunctionEmitter, serial: usize, comptime name: []const u8, value: Ir.ValueId) Error!void {
        try self.write("  %t{d}.{s}.negative = icmp slt i64 %v{d}, 0\n", .{ serial, name, value });
        try self.write("  %t{d}.{s}.wrapped = add i64 %t{d}.count, %v{d}\n", .{ serial, name, serial, value });
        try self.write("  %t{d}.{s} = select i1 %t{d}.{s}.negative, i64 %t{d}.{s}.wrapped, i64 %v{d}\n", .{
            serial,
            name,
            serial,
            name,
            serial,
            name,
            value,
        });
    }

    fn collectionInfo(self: *FunctionEmitter, type_value: Ir.Type) Error!CollectionInfo {
        const structure = type_value.structureIndex() orelse return error.UnsupportedType;
        if (structure >= self.program.structures.len) return error.InvalidProgram;
        const collection = self.program.structures[structure].collection orelse return error.UnsupportedType;
        return .{ .element = collection.element, .length = collection.length, .view = collection.view };
    }

    fn emitLocalAddress(self: *FunctionEmitter, value: Ir.Instruction.LocalAddress) Error!void {
        if (value.local >= self.function.local_types.len or try self.valueType(value.result) != .address)
            return error.InvalidProgram;
        try self.write("  %v{d} = getelementptr {s}, ptr %local{d}, i32 0\n", .{
            value.result,
            try llvmType(self.allocator, self.program, self.function.local_types[value.local]),
            value.local,
        });
    }

    fn emitReferenceLoad(self: *FunctionEmitter, value: Ir.Instruction.ReferenceLoad) Error!void {
        if (try self.valueType(value.reference) != .address) return error.InvalidProgram;
        try self.write("  %v{d} = load {s}, ptr %v{d}\n", .{
            value.result,
            try llvmType(self.allocator, self.program, try self.valueType(value.result)),
            value.reference,
        });
    }

    fn emitReferenceStore(self: *FunctionEmitter, value: Ir.Instruction.ReferenceStore) Error!void {
        if (try self.valueType(value.reference) != .address) return error.InvalidProgram;
        try self.write("  store {s} %v{d}, ptr %v{d}\n", .{
            try llvmType(self.allocator, self.program, try self.valueType(value.operand)),
            value.operand,
            value.reference,
        });
    }

    fn emitReferenceField(self: *FunctionEmitter, value: Ir.Instruction.ReferenceField) Error!void {
        if (value.structure >= self.program.structures.len or
            value.field >= self.program.structures[value.structure].fields.len or
            try self.valueType(value.reference) != .address or
            try self.valueType(value.result) != .address)
        {
            return error.InvalidProgram;
        }
        try self.write("  %v{d} = getelementptr {s}, ptr %v{d}, i32 0, i32 {d}\n", .{
            value.result,
            try llvmType(self.allocator, self.program, Ir.Type.structure(value.structure)),
            value.reference,
            value.field,
        });
    }

    fn emitNegate(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Unary) Error!void {
        const type_value = try self.valueType(value.operand);
        if (value.operator != .negate) return error.UnsupportedInstruction;
        if (type_value.isFloat()) return self.write("  %v{d} = fneg {s} %v{d}\n", .{
            value.result,
            try llvmType(self.allocator, self.program, type_value),
            value.operand,
        });
        if (!type_value.isInteger()) return error.UnsupportedInstruction;
        const signed = type_value.isSignedInteger();
        try self.emitOverflowOperation(
            block_id,
            value.result,
            if (signed) "ssub" else "usub",
            type_value,
            "0",
            try std.fmt.allocPrint(self.allocator, "%v{d}", .{value.operand}),
        );
    }

    fn emitBinary(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Binary) Error!void {
        const left_type = try self.valueType(value.left);
        const type_name = try llvmType(self.allocator, self.program, left_type);
        switch (value.operator) {
            .add, .subtract, .multiply => {
                if (left_type.isFloat()) return self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
                    value.result,
                    switch (value.operator) {
                        .add => "fadd",
                        .subtract => "fsub",
                        .multiply => "fmul",
                        else => unreachable,
                    },
                    type_name,
                    value.left,
                    value.right,
                });
                if (!left_type.isInteger()) return error.UnsupportedInstruction;
                const prefix = if (left_type.isSignedInteger()) "s" else "u";
                const operation = switch (value.operator) {
                    .add => "add",
                    .subtract => "sub",
                    .multiply => "mul",
                    else => unreachable,
                };
                try self.emitOverflowOperation(
                    block_id,
                    value.result,
                    try std.fmt.allocPrint(self.allocator, "{s}{s}", .{ prefix, operation }),
                    left_type,
                    try std.fmt.allocPrint(self.allocator, "%v{d}", .{value.left}),
                    try std.fmt.allocPrint(self.allocator, "%v{d}", .{value.right}),
                );
            },
            .divide, .remainder => if (left_type.isFloat())
                try self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
                    value.result,
                    if (value.operator == .divide) "fdiv" else "frem",
                    type_name,
                    value.left,
                    value.right,
                })
            else
                try self.emitDivision(block_id, value, left_type),
            .shift_left, .shift_right => try self.emitShift(block_id, value, left_type),
            .minimum, .maximum => try self.emitFloatMinimumMaximum(value, left_type),
            .bit_and, .bit_xor => try self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
                value.result,
                if (value.operator == .bit_and) "and" else "xor",
                type_name,
                value.left,
                value.right,
            }),
            .less, .less_equal, .greater, .greater_equal, .equal, .not_equal => {
                if (left_type.isFloat()) {
                    const predicate = switch (value.operator) {
                        .equal => "oeq",
                        .not_equal => "une",
                        .less => "olt",
                        .less_equal => "ole",
                        .greater => "ogt",
                        .greater_equal => "oge",
                        else => unreachable,
                    };
                    return self.write("  %v{d} = fcmp {s} {s} %v{d}, %v{d}\n", .{
                        value.result,
                        predicate,
                        type_name,
                        value.left,
                        value.right,
                    });
                }
                if (!left_type.isInteger() and left_type != .bool) return error.UnsupportedInstruction;
                const predicate = switch (value.operator) {
                    .equal => "eq",
                    .not_equal => "ne",
                    .less => if (left_type.isSignedInteger()) "slt" else "ult",
                    .less_equal => if (left_type.isSignedInteger()) "sle" else "ule",
                    .greater => if (left_type.isSignedInteger()) "sgt" else "ugt",
                    .greater_equal => if (left_type.isSignedInteger()) "sge" else "uge",
                    else => unreachable,
                };
                try self.write("  %v{d} = icmp {s} {s} %v{d}, %v{d}\n", .{
                    value.result,
                    predicate,
                    type_name,
                    value.left,
                    value.right,
                });
            },
        }
    }

    fn emitFloatMinimumMaximum(
        self: *FunctionEmitter,
        value: Ir.Instruction.Binary,
        type_value: Ir.Type,
    ) Error!void {
        if (!type_value.isFloat()) return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        const type_name = try llvmType(self.allocator, self.program, type_value);
        const integer_name = if (type_value == .float32) "i32" else "i64";
        try self.write("  %t{d}.left_nan = fcmp uno {s} %v{d}, %v{d}\n", .{
            serial, type_name, value.left, value.left,
        });
        try self.write("  %t{d}.right_nan = fcmp uno {s} %v{d}, %v{d}\n", .{
            serial, type_name, value.right, value.right,
        });
        try self.write("  %t{d}.ordered = fcmp {s} {s} %v{d}, %v{d}\n", .{
            serial,
            if (value.operator == .minimum) "olt" else "ogt",
            type_name,
            value.left,
            value.right,
        });
        try self.write("  %t{d}.equal = fcmp oeq {s} %v{d}, %v{d}\n", .{
            serial, type_name, value.left, value.right,
        });
        try self.write("  %t{d}.left_bits = bitcast {s} %v{d} to {s}\n", .{
            serial, type_name, value.left, integer_name,
        });
        try self.write("  %t{d}.left_negative = icmp slt {s} %t{d}.left_bits, 0\n", .{
            serial, integer_name, serial,
        });
        try self.write("  %t{d}.equal_value = select i1 %t{d}.left_negative, {s} %v{d}, {s} %v{d}\n", .{
            serial,
            serial,
            type_name,
            if (value.operator == .minimum) value.left else value.right,
            type_name,
            if (value.operator == .minimum) value.right else value.left,
        });
        try self.write("  %t{d}.ordered_value = select i1 %t{d}.ordered, {s} %v{d}, {s} %v{d}\n", .{
            serial, serial, type_name, value.left, type_name, value.right,
        });
        try self.write("  %t{d}.finite_value = select i1 %t{d}.equal, {s} %t{d}.equal_value, {s} %t{d}.ordered_value\n", .{
            serial, serial, type_name, serial, type_name, serial,
        });
        try self.write("  %t{d}.right_checked = select i1 %t{d}.right_nan, {s} %v{d}, {s} %t{d}.finite_value\n", .{
            serial, serial, type_name, value.left, type_name, serial,
        });
        try self.write("  %v{d} = select i1 %t{d}.left_nan, {s} %v{d}, {s} %t{d}.right_checked\n", .{
            value.result, serial, type_name, value.right, type_name, serial,
        });
    }

    fn emitOverflowOperation(
        self: *FunctionEmitter,
        block_id: usize,
        result: Ir.ValueId,
        operation: []const u8,
        type_value: Ir.Type,
        left: []const u8,
        right: []const u8,
    ) Error!void {
        const serial = self.nextTemporary();
        const width = type_value.bitWidth();
        try self.write("  %t{d}.pair = call {{ i{d}, i1 }} @llvm.{s}.with.overflow.i{d}(i{d} {s}, i{d} {s})\n", .{
            serial,
            width,
            operation,
            width,
            width,
            left,
            width,
            right,
        });
        try self.write("  %v{d} = extractvalue {{ i{d}, i1 }} %t{d}.pair, 0\n", .{ result, width, serial });
        try self.write("  %t{d}.overflow = extractvalue {{ i{d}, i1 }} %t{d}.pair, 1\n", .{ serial, width, serial });
        try self.write("  br i1 %t{d}.overflow, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
    }

    fn emitDivision(
        self: *FunctionEmitter,
        block_id: usize,
        value: Ir.Instruction.Binary,
        type_value: Ir.Type,
    ) Error!void {
        if (!type_value.isInteger()) return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        const type_name = try llvmType(self.allocator, self.program, type_value);
        try self.write("  %t{d}.zero = icmp eq {s} %v{d}, 0\n", .{ serial, type_name, value.right });
        if (type_value.isSignedInteger()) {
            try self.write("  %t{d}.minimum = icmp eq {s} %v{d}, {d}\n", .{
                serial,
                type_name,
                value.left,
                integerMinimum(type_value),
            });
            try self.write("  %t{d}.minusone = icmp eq {s} %v{d}, -1\n", .{ serial, type_name, value.right });
            try self.write("  %t{d}.overflow = and i1 %t{d}.minimum, %t{d}.minusone\n", .{ serial, serial, serial });
            try self.write("  %t{d}.invalid = or i1 %t{d}.zero, %t{d}.overflow\n", .{ serial, serial, serial });
        } else {
            try self.write("  %t{d}.invalid = xor i1 %t{d}.zero, false\n", .{ serial, serial });
        }
        try self.write("  br i1 %t{d}.invalid, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
        const operation = if (type_value.isSignedInteger())
            (if (value.operator == .divide) "sdiv" else "srem")
        else if (value.operator == .divide) "udiv" else "urem";
        try self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
            value.result,
            operation,
            type_name,
            value.left,
            value.right,
        });
    }

    fn emitShift(
        self: *FunctionEmitter,
        block_id: usize,
        value: Ir.Instruction.Binary,
        left_type: Ir.Type,
    ) Error!void {
        if (!left_type.isInteger()) return error.UnsupportedInstruction;
        const right_type = try self.valueType(value.right);
        if (!right_type.isInteger()) return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        const right_name = try llvmType(self.allocator, self.program, right_type);
        if (right_type.isSignedInteger()) {
            try self.write("  %t{d}.negative = icmp slt {s} %v{d}, 0\n", .{ serial, right_name, value.right });
        } else {
            try self.write("  %t{d}.negative = xor i1 false, false\n", .{serial});
        }
        try self.write("  %t{d}.large = icmp uge {s} %v{d}, {d}\n", .{
            serial,
            right_name,
            value.right,
            left_type.bitWidth(),
        });
        try self.write("  %t{d}.invalid = or i1 %t{d}.negative, %t{d}.large\n", .{ serial, serial, serial });
        try self.write("  br i1 %t{d}.invalid, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
        const left_name = try llvmType(self.allocator, self.program, left_type);
        if (right_type.bitWidth() < left_type.bitWidth()) {
            try self.write("  %t{d}.count = zext {s} %v{d} to {s}\n", .{ serial, right_name, value.right, left_name });
        } else if (right_type.bitWidth() > left_type.bitWidth()) {
            try self.write("  %t{d}.count = trunc {s} %v{d} to {s}\n", .{ serial, right_name, value.right, left_name });
        } else {
            try self.write("  %t{d}.count = select i1 true, {s} %v{d}, {s} %v{d}\n", .{
                serial,
                left_name,
                value.right,
                left_name,
                value.right,
            });
        }
        try self.write("  %v{d} = {s} {s} %v{d}, %t{d}.count\n", .{
            value.result,
            if (value.operator == .shift_left) "shl" else "lshr",
            left_name,
            value.left,
            serial,
        });
    }

    fn emitConvert(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Convert) Error!void {
        if (value.source == value.target) return self.copyValue(value.result, value.operand);
        if (value.source == .float32 and value.target == .float64)
            return self.write("  %v{d} = fpext float %v{d} to double\n", .{ value.result, value.operand });
        if (value.source.isInteger() and value.target.isFloat())
            return self.emitIntegerToFloat(block_id, value);
        if (!value.source.isInteger() or !value.target.isInteger()) return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        const source_name = try llvmType(self.allocator, self.program, value.source);
        try self.write("  %t{d}.wide = {s} {s} %v{d} to i128\n", .{
            serial,
            if (value.source.isSignedInteger()) "sext" else "zext",
            source_name,
            value.operand,
        });
        try self.write("  %t{d}.low = icmp slt i128 %t{d}.wide, {d}\n", .{
            serial,
            serial,
            integerMinimum(value.target),
        });
        try self.write("  %t{d}.high = icmp sgt i128 %t{d}.wide, {d}\n", .{
            serial,
            serial,
            integerMaximum(value.target),
        });
        try self.write("  %t{d}.invalid = or i1 %t{d}.low, %t{d}.high\n", .{ serial, serial, serial });
        try self.emitConversionFailure(block_id, serial, value, false);
        try self.write("  %v{d} = trunc i128 %t{d}.wide to {s}\n", .{
            value.result,
            serial,
            try llvmType(self.allocator, self.program, value.target),
        });
    }

    fn emitIntegerToFloat(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Convert) Error!void {
        const source_name = try llvmType(self.allocator, self.program, value.source);
        const target_name = try llvmType(self.allocator, self.program, value.target);
        const signed = value.source.isSignedInteger();
        try self.write("  %v{d} = {s} {s} %v{d} to {s}\n", .{
            value.result,
            if (signed) "sitofp" else "uitofp",
            source_name,
            value.operand,
            target_name,
        });
        if (!value.checked) return;

        const serial = self.nextTemporary();
        const width = value.source.bitWidth();
        const floating_suffix = if (value.target == .float32) "f32" else "f64";
        try self.write("  %t{d}.roundtrip = call {s} @llvm.{s}.sat.i{d}.{s}({s} %v{d})\n", .{
            serial,
            source_name,
            if (signed) "fptosi" else "fptoui",
            width,
            floating_suffix,
            target_name,
            value.result,
        });
        try self.write("  %t{d}.same = icmp eq {s} %t{d}.roundtrip, %v{d}\n", .{
            serial,
            source_name,
            serial,
            value.operand,
        });
        const precision: u7 = if (value.target == .float32) 24 else 53;
        const maximum_is_inexact = if (signed) width - 1 > precision else width > precision;
        if (maximum_is_inexact) {
            try self.write("  %t{d}.maximum = icmp eq {s} %v{d}, {d}\n", .{
                serial,
                source_name,
                value.operand,
                integerMaximum(value.source),
            });
            try self.write("  %t{d}.not_maximum = xor i1 %t{d}.maximum, true\n", .{ serial, serial });
            try self.write("  %t{d}.exact = and i1 %t{d}.same, %t{d}.not_maximum\n", .{ serial, serial, serial });
        } else {
            try self.write("  %t{d}.exact = xor i1 %t{d}.same, false\n", .{ serial, serial });
        }
        try self.emitConversionFailure(block_id, serial, value, true);
    }

    fn emitCall(self: *FunctionEmitter, value: Ir.Instruction.Call) Error!void {
        if (value.function >= self.program.functions.len) return error.InvalidProgram;
        const callee = self.program.functions[value.function];
        if (callee.parameter_types.len != value.arguments.len) return error.InvalidProgram;
        try self.output.appendSlice(self.allocator, "  ");
        if (value.result) |result| try self.write("%v{d} = ", .{result});
        try self.write("call fastcc {s} @sx_{d}(", .{ try llvmType(self.allocator, self.program, callee.return_type), value.function });
        for (value.arguments, 0..) |argument, index| {
            if (index != 0) try self.output.appendSlice(self.allocator, ", ");
            try self.write("{s} %v{d}", .{ try llvmType(self.allocator, self.program, callee.parameter_types[index]), argument });
        }
        try self.output.appendSlice(self.allocator, ")\n");
    }

    fn emitBoundaryCall(self: *FunctionEmitter, value: Ir.Instruction.BoundaryCall) Error!void {
        if (value.function >= self.boundaries.len) return error.InvalidProgram;
        const boundary = self.boundaries[value.function];
        if (!supportsDirectBoundary(boundary)) return error.UnsupportedType;
        if (boundary.parameters.len != value.arguments.len) return error.InvalidProgram;
        try self.output.appendSlice(self.allocator, "  ");
        if (boundary.return_type == .void) {
            if (value.result != null) return error.InvalidProgram;
        } else {
            const result = value.result orelse return error.InvalidProgram;
            if (try self.valueType(result) != boundary.return_type) return error.InvalidProgram;
            try self.write("%v{d} = ", .{result});
        }
        try self.write("call {s} @{s}(", .{
            try llvmType(self.allocator, self.program, boundary.return_type),
            boundary.source_name,
        });
        for (value.arguments, 0..) |argument, index| {
            if (try self.valueType(argument) != boundary.parameters[index]) return error.InvalidProgram;
            if (index != 0) try self.output.appendSlice(self.allocator, ", ");
            try self.write("{s} %v{d}", .{
                try llvmType(self.allocator, self.program, boundary.parameters[index]),
                argument,
            });
        }
        try self.output.appendSlice(self.allocator, ")\n");
    }

    fn emitPrint(self: *FunctionEmitter, value: Ir.Instruction.Print) Error!void {
        const type_value = try self.valueType(value.value);
        const serial = self.nextTemporary();
        if (type_value == .bool) {
            try self.write("  %t{d}.text = select i1 %v{d}, ptr @.true, ptr @.false\n", .{ serial, value.value });
            try self.write("  %t{d}.print = call i32 (i32, ptr, ...) @dprintf(i32 1, ptr @{s}, ptr %t{d}.text)\n", .{
                serial,
                if (value.newline) ".fmt.boolean" else ".fmt.boolean.inline",
                serial,
            });
            return;
        }
        if (!type_value.isInteger()) return error.UnsupportedType;
        const type_name = try llvmType(self.allocator, self.program, type_value);
        if (type_value.bitWidth() < 64) {
            try self.write("  %t{d}.wide = {s} {s} %v{d} to i64\n", .{
                serial,
                if (type_value.isSignedInteger()) "sext" else "zext",
                type_name,
                value.value,
            });
        } else {
            try self.write("  %t{d}.wide = select i1 true, i64 %v{d}, i64 %v{d}\n", .{
                serial,
                value.value,
                value.value,
            });
        }
        const format = if (type_value.isSignedInteger())
            (if (value.newline) ".fmt.signed" else ".fmt.signed.inline")
        else if (value.newline) ".fmt.unsigned" else ".fmt.unsigned.inline";
        try self.write("  %t{d}.print = call i32 (i32, ptr, ...) @dprintf(i32 1, ptr @{s}, i64 %t{d}.wide)\n", .{
            serial,
            format,
            serial,
        });
    }

    fn emitTerminator(self: *FunctionEmitter, terminator: Ir.Terminator) Error!void {
        switch (terminator) {
            .jump => |target| try self.write("  br label %b{d}\n", .{target}),
            .branch => |branch| try self.write("  br i1 %v{d}, label %b{d}, label %b{d}\n", .{
                branch.condition,
                branch.then_block,
                branch.else_block,
            }),
            .return_value => |value| try self.write("  ret {s} %v{d}\n", .{
                try llvmType(self.allocator, self.program, self.function.return_type),
                value,
            }),
            .return_void => try self.output.appendSlice(self.allocator, "  ret void\n"),
            .panic => return error.UnsupportedInstruction,
        }
    }

    fn valueType(self: *FunctionEmitter, value: Ir.ValueId) Error!Ir.Type {
        if (value >= self.function.value_types.len) return error.InvalidProgram;
        return self.function.value_types[value];
    }

    fn nextTemporary(self: *FunctionEmitter) usize {
        const temporary = self.temporary;
        self.temporary += 1;
        return temporary;
    }

    fn write(self: *FunctionEmitter, comptime format: []const u8, arguments: anytype) Error!void {
        return appendFmt(self.output, self.allocator, format, arguments);
    }
};

fn emitBoundaryDeclarations(
    output: *std.ArrayList(u8),
    allocator: Allocator,
    program: Ir.Program,
    boundaries: []const Silex.Boundary.Function,
    direct_sites_by_function: []const usize,
) Error!void {
    if (direct_sites_by_function.len != boundaries.len) return error.InvalidProgram;
    var emitted = false;
    boundary: for (boundaries, 0..) |function, index| {
        if (direct_sites_by_function[index] == 0) continue;
        if (!supportsDirectBoundary(function)) return error.UnsupportedType;
        for (boundaries[0..index], direct_sites_by_function[0..index]) |previous, previous_sites| {
            if (previous_sites == 0 or !std.mem.eql(u8, previous.source_name, function.source_name)) continue;
            if (!std.mem.eql(u8, previous.provider, function.provider) or
                previous.return_type != function.return_type or
                !std.mem.eql(Ir.Type, previous.parameters, function.parameters))
            {
                std.debug.print(
                    "silex LLVM evaluation: boundary symbol '{s}' has conflicting providers or signatures\n",
                    .{function.source_name},
                );
                return error.InvalidProgram;
            }
            continue :boundary;
        }
        try appendFmt(output, allocator, "declare {s} @{s}(", .{
            try llvmType(allocator, program, function.return_type),
            function.source_name,
        });
        for (function.parameters, 0..) |parameter, parameter_index| {
            if (parameter_index != 0) try output.appendSlice(allocator, ", ");
            try output.appendSlice(allocator, try llvmType(allocator, program, parameter));
        }
        try output.appendSlice(allocator, ")\n");
        emitted = true;
    }
    if (emitted) try output.append(allocator, '\n');
}

fn supportsDirectBoundary(function: Silex.Boundary.Function) bool {
    if (!supportsBoundaryType(function.return_type)) return false;
    for (function.parameters) |parameter| if (!supportsBoundaryType(parameter)) return false;
    return true;
}

fn supportsBoundaryType(type_value: Ir.Type) bool {
    return switch (type_value) {
        .void,
        .bool,
        .int8,
        .uint8,
        .int16,
        .uint16,
        .int32,
        .uint32,
        .int,
        .uint,
        .float32,
        .float64,
        .address,
        => true,
        else => false,
    };
}

const CollectionInfo = struct {
    element: Ir.Type,
    length: ?usize,
    view: bool,
};

fn plainValue(program: Ir.Program, type_value: Ir.Type, depth: usize) bool {
    if (type_value.isNumeric() or type_value == .bool) return true;
    const index = type_value.structureIndex() orelse return false;
    if (index >= program.structures.len or depth >= program.structures.len) return false;
    const structure = program.structures[index];
    if (structure.is_class or structure.is_static or structure.is_protocol or structure.collection != null)
        return false;
    for (structure.fields) |field| if (!plainValue(program, field.type, depth + 1)) return false;
    return true;
}

fn llvmType(allocator: Allocator, program: Ir.Program, type_value: Ir.Type) Error![]const u8 {
    if (type_value.structureIndex()) |structure_index| {
        if (structure_index >= program.structures.len) return error.InvalidProgram;
        return std.fmt.allocPrint(allocator, "%sx.type.{d}", .{structure_index});
    }
    return switch (type_value) {
        .void => "void",
        .bool => "i1",
        .int8, .uint8 => "i8",
        .int16, .uint16 => "i16",
        .int32, .uint32 => "i32",
        .int, .uint => "i64",
        .float32 => "float",
        .float64 => "double",
        .address => "ptr",
        else => error.UnsupportedType,
    };
}

fn normalize(bits: u64, type_value: Ir.Type) u64 {
    const width = type_value.bitWidth();
    if (width == 64) return bits;
    return bits & ((@as(u64, 1) << @intCast(width)) - 1);
}

fn integerMinimum(type_value: Ir.Type) i128 {
    if (!type_value.isSignedInteger()) return 0;
    return -(@as(i128, 1) << @intCast(type_value.bitWidth() - 1));
}

fn integerMaximum(type_value: Ir.Type) i128 {
    return if (type_value.isSignedInteger())
        (@as(i128, 1) << @intCast(type_value.bitWidth() - 1)) - 1
    else
        (@as(i128, 1) << @intCast(type_value.bitWidth())) - 1;
}

fn appendFmt(
    output: *std.ArrayList(u8),
    allocator: Allocator,
    comptime format: []const u8,
    arguments: anytype,
) Allocator.Error!void {
    try output.appendSlice(allocator, try std.fmt.allocPrint(allocator, format, arguments));
}

fn emitSourceFiles(output: *std.ArrayList(u8), allocator: Allocator, program: Ir.Program) Allocator.Error!void {
    for (program.files, 0..) |path, index| {
        try appendFmt(output, allocator, "@sx.file.{d} = private constant [{d} x i8] c\"", .{ index, path.len + 1 });
        for (path) |byte| try appendFmt(output, allocator, "\\{X:0>2}", .{byte});
        try output.appendSlice(allocator, "\\00\"\n");
    }
}
