const std = @import("std");
const Silex = @import("silex_optimizer_api");

const Allocator = std.mem.Allocator;
const Ir = Silex.Ir;

pub const Error = Allocator.Error || error{
    InvalidProgram,
    UnsupportedInstruction,
    UnsupportedType,
};

pub fn emit(allocator: Allocator, program: Ir.Program) Error![]u8 {
    var output: std.ArrayList(u8) = .empty;
    try output.appendSlice(allocator,
        \\; Generated by the Silex optimizer oracle. Development use only.
        \\@.fmt.signed = private constant [6 x i8] c"%lld\0A\00"
        \\@.fmt.signed.inline = private constant [5 x i8] c"%lld\00"
        \\@.fmt.unsigned = private constant [6 x i8] c"%llu\0A\00"
        \\@.fmt.unsigned.inline = private constant [5 x i8] c"%llu\00"
        \\@.fmt.boolean = private constant [4 x i8] c"%s\0A\00"
        \\@.fmt.boolean.inline = private constant [3 x i8] c"%s\00"
        \\@.true = private constant [5 x i8] c"true\00"
        \\@.false = private constant [6 x i8] c"false\00"
        \\
        \\declare i32 @printf(ptr, ...)
        \\declare void @llvm.trap()
        \\
    );
    for ([_]u7{ 8, 16, 32, 64 }) |width| {
        for ([_][]const u8{ "sadd", "ssub", "smul", "uadd", "usub", "umul" }) |operation| {
            try appendFmt(
                &output,
                allocator,
                "declare {{ i{d}, i1 }} @llvm.{s}.with.overflow.i{d}(i{d}, i{d})\n",
                .{ width, operation, width, width, width },
            );
        }
    }
    try output.append(allocator, '\n');

    var main_function: ?usize = null;
    for (program.functions, 0..) |function, function_id| {
        if (std.mem.eql(u8, function.name, "main")) {
            if (main_function != null) return error.InvalidProgram;
            main_function = function_id;
        }
        var emitter: FunctionEmitter = .{
            .allocator = allocator,
            .output = &output,
            .program = program,
            .function = function,
            .function_id = function_id,
        };
        try emitter.emit();
    }
    const main_id = main_function orelse return error.InvalidProgram;
    const main = program.functions[main_id];
    if (main.parameter_types.len != 0 or main.return_type != .void) return error.UnsupportedType;
    try appendFmt(&output, allocator,
        \\define i32 @main() {{
        \\entry:
        \\  call void @sx_{d}()
        \\  ret i32 0
        \\}}
        \\
    , .{main_id});
    return output.toOwnedSlice(allocator);
}

const FunctionEmitter = struct {
    allocator: Allocator,
    output: *std.ArrayList(u8),
    program: Ir.Program,
    function: Ir.Function,
    function_id: usize,
    temporary: usize = 0,

    fn emit(self: *FunctionEmitter) Error!void {
        if (self.function.capture_types.len != 0) return error.UnsupportedInstruction;
        try self.write("define {s} @sx_{d}(", .{ try llvmType(self.function.return_type), self.function_id });
        for (self.function.parameter_types, 0..) |type_value, index| {
            if (index != 0) try self.output.appendSlice(self.allocator, ", ");
            try self.write("{s} %v{d}", .{ try llvmType(type_value), index });
        }
        try self.output.appendSlice(self.allocator, ") {\n");
        for (self.function.blocks, 0..) |block, block_id| {
            try self.write("b{d}:\n", .{block_id});
            if (block_id == 0) {
                for (self.function.local_types, 0..) |type_value, local| {
                    try self.write("  %local{d} = alloca {s}\n", .{ local, try llvmType(type_value) });
                }
            }
            for (block.instructions) |instruction| try self.emitInstruction(block_id, instruction);
            try self.emitTerminator(block.terminator);
        }
        try self.output.appendSlice(self.allocator,
            \\trap:
            \\  call void @llvm.trap()
            \\  unreachable
            \\}
            \\
        );
    }

    fn emitInstruction(self: *FunctionEmitter, block_id: usize, instruction: Ir.Instruction) Error!void {
        switch (instruction) {
            .constant_int => |value| {
                const type_value = try self.valueType(value.result);
                const bits = normalize(value.bits, type_value);
                try self.write("  %v{d} = add {s} 0, {d}\n", .{ value.result, try llvmType(type_value), bits });
            },
            .constant_bool => |value| try self.write(
                "  %v{d} = xor i1 false, {s}\n",
                .{ value.result, if (value.value) "true" else "false" },
            ),
            .constant_float32 => |value| try self.write(
                "  %v{d} = bitcast i32 {d} to float\n",
                .{ value.result, value.bits },
            ),
            .constant_float64 => |value| try self.write(
                "  %v{d} = bitcast i64 {d} to double\n",
                .{ value.result, value.bits },
            ),
            .copy => |value| try self.copyValue(value.result, value.operand),
            .local_load => |value| try self.write(
                "  %v{d} = load {s}, ptr %local{d}\n",
                .{ value.result, try llvmType(try self.valueType(value.result)), value.local },
            ),
            .local_store => |value| try self.write(
                "  store {s} %v{d}, ptr %local{d}\n",
                .{ try llvmType(try self.valueType(value.operand)), value.operand, value.local },
            ),
            .unary => |value| try self.emitNegate(block_id, value),
            .binary => |value| try self.emitBinary(block_id, value),
            .convert => |value| try self.emitConvert(block_id, value),
            .call => |value| try self.emitCall(value),
            .print => |value| try self.emitPrint(value),
            else => return error.UnsupportedInstruction,
        }
    }

    fn copyValue(self: *FunctionEmitter, result: Ir.ValueId, operand: Ir.ValueId) Error!void {
        const type_name = try llvmType(try self.valueType(result));
        try self.write("  %v{d} = select i1 true, {s} %v{d}, {s} %v{d}\n", .{
            result,
            type_name,
            operand,
            type_name,
            operand,
        });
    }

    fn emitNegate(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Unary) Error!void {
        const type_value = try self.valueType(value.operand);
        if (value.operator != .negate) return error.UnsupportedInstruction;
        if (type_value.isFloat()) return self.write("  %v{d} = fneg {s} %v{d}\n", .{
            value.result,
            try llvmType(type_value),
            value.operand,
        });
        if (!type_value.isInteger()) return error.UnsupportedInstruction;
        const signed = type_value.isSignedInteger();
        try self.emitOverflowOperation(
            block_id,
            value.result,
            if (signed) "ssub" else "usub",
            type_value,
            "0",
            try std.fmt.allocPrint(self.allocator, "%v{d}", .{value.operand}),
        );
    }

    fn emitBinary(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Binary) Error!void {
        const left_type = try self.valueType(value.left);
        const type_name = try llvmType(left_type);
        switch (value.operator) {
            .add, .subtract, .multiply => {
                if (left_type.isFloat()) return self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
                    value.result,
                    switch (value.operator) {
                        .add => "fadd",
                        .subtract => "fsub",
                        .multiply => "fmul",
                        else => unreachable,
                    },
                    type_name,
                    value.left,
                    value.right,
                });
                if (!left_type.isInteger()) return error.UnsupportedInstruction;
                const prefix = if (left_type.isSignedInteger()) "s" else "u";
                const operation = switch (value.operator) {
                    .add => "add",
                    .subtract => "sub",
                    .multiply => "mul",
                    else => unreachable,
                };
                try self.emitOverflowOperation(
                    block_id,
                    value.result,
                    try std.fmt.allocPrint(self.allocator, "{s}{s}", .{ prefix, operation }),
                    left_type,
                    try std.fmt.allocPrint(self.allocator, "%v{d}", .{value.left}),
                    try std.fmt.allocPrint(self.allocator, "%v{d}", .{value.right}),
                );
            },
            .divide, .remainder => if (left_type.isFloat())
                try self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
                    value.result,
                    if (value.operator == .divide) "fdiv" else "frem",
                    type_name,
                    value.left,
                    value.right,
                })
            else
                try self.emitDivision(block_id, value, left_type),
            .shift_left, .shift_right => try self.emitShift(block_id, value, left_type),
            .bit_and, .bit_xor => try self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
                value.result,
                if (value.operator == .bit_and) "and" else "xor",
                type_name,
                value.left,
                value.right,
            }),
            .less, .less_equal, .greater, .greater_equal, .equal, .not_equal => {
                if (left_type.isFloat()) {
                    const predicate = switch (value.operator) {
                        .equal => "oeq",
                        .not_equal => "une",
                        .less => "olt",
                        .less_equal => "ole",
                        .greater => "ogt",
                        .greater_equal => "oge",
                        else => unreachable,
                    };
                    return self.write("  %v{d} = fcmp {s} {s} %v{d}, %v{d}\n", .{
                        value.result,
                        predicate,
                        type_name,
                        value.left,
                        value.right,
                    });
                }
                if (!left_type.isInteger() and left_type != .bool) return error.UnsupportedInstruction;
                const predicate = switch (value.operator) {
                    .equal => "eq",
                    .not_equal => "ne",
                    .less => if (left_type.isSignedInteger()) "slt" else "ult",
                    .less_equal => if (left_type.isSignedInteger()) "sle" else "ule",
                    .greater => if (left_type.isSignedInteger()) "sgt" else "ugt",
                    .greater_equal => if (left_type.isSignedInteger()) "sge" else "uge",
                    else => unreachable,
                };
                try self.write("  %v{d} = icmp {s} {s} %v{d}, %v{d}\n", .{
                    value.result,
                    predicate,
                    type_name,
                    value.left,
                    value.right,
                });
            },
        }
    }

    fn emitOverflowOperation(
        self: *FunctionEmitter,
        block_id: usize,
        result: Ir.ValueId,
        operation: []const u8,
        type_value: Ir.Type,
        left: []const u8,
        right: []const u8,
    ) Error!void {
        const serial = self.nextTemporary();
        const width = type_value.bitWidth();
        try self.write("  %t{d}.pair = call {{ i{d}, i1 }} @llvm.{s}.with.overflow.i{d}(i{d} {s}, i{d} {s})\n", .{
            serial,
            width,
            operation,
            width,
            width,
            left,
            width,
            right,
        });
        try self.write("  %v{d} = extractvalue {{ i{d}, i1 }} %t{d}.pair, 0\n", .{ result, width, serial });
        try self.write("  %t{d}.overflow = extractvalue {{ i{d}, i1 }} %t{d}.pair, 1\n", .{ serial, width, serial });
        try self.write("  br i1 %t{d}.overflow, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
    }

    fn emitDivision(
        self: *FunctionEmitter,
        block_id: usize,
        value: Ir.Instruction.Binary,
        type_value: Ir.Type,
    ) Error!void {
        if (!type_value.isInteger()) return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        const type_name = try llvmType(type_value);
        try self.write("  %t{d}.zero = icmp eq {s} %v{d}, 0\n", .{ serial, type_name, value.right });
        if (type_value.isSignedInteger()) {
            try self.write("  %t{d}.minimum = icmp eq {s} %v{d}, {d}\n", .{
                serial,
                type_name,
                value.left,
                integerMinimum(type_value),
            });
            try self.write("  %t{d}.minusone = icmp eq {s} %v{d}, -1\n", .{ serial, type_name, value.right });
            try self.write("  %t{d}.overflow = and i1 %t{d}.minimum, %t{d}.minusone\n", .{ serial, serial, serial });
            try self.write("  %t{d}.invalid = or i1 %t{d}.zero, %t{d}.overflow\n", .{ serial, serial, serial });
        } else {
            try self.write("  %t{d}.invalid = xor i1 %t{d}.zero, false\n", .{ serial, serial });
        }
        try self.write("  br i1 %t{d}.invalid, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
        const operation = if (type_value.isSignedInteger())
            (if (value.operator == .divide) "sdiv" else "srem")
        else if (value.operator == .divide) "udiv" else "urem";
        try self.write("  %v{d} = {s} {s} %v{d}, %v{d}\n", .{
            value.result,
            operation,
            type_name,
            value.left,
            value.right,
        });
    }

    fn emitShift(
        self: *FunctionEmitter,
        block_id: usize,
        value: Ir.Instruction.Binary,
        left_type: Ir.Type,
    ) Error!void {
        if (!left_type.isInteger()) return error.UnsupportedInstruction;
        const right_type = try self.valueType(value.right);
        if (!right_type.isInteger()) return error.UnsupportedInstruction;
        const serial = self.nextTemporary();
        const right_name = try llvmType(right_type);
        if (right_type.isSignedInteger()) {
            try self.write("  %t{d}.negative = icmp slt {s} %v{d}, 0\n", .{ serial, right_name, value.right });
        } else {
            try self.write("  %t{d}.negative = xor i1 false, false\n", .{serial});
        }
        try self.write("  %t{d}.large = icmp uge {s} %v{d}, {d}\n", .{
            serial,
            right_name,
            value.right,
            left_type.bitWidth(),
        });
        try self.write("  %t{d}.invalid = or i1 %t{d}.negative, %t{d}.large\n", .{ serial, serial, serial });
        try self.write("  br i1 %t{d}.invalid, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
        const left_name = try llvmType(left_type);
        if (right_type.bitWidth() < left_type.bitWidth()) {
            try self.write("  %t{d}.count = zext {s} %v{d} to {s}\n", .{ serial, right_name, value.right, left_name });
        } else if (right_type.bitWidth() > left_type.bitWidth()) {
            try self.write("  %t{d}.count = trunc {s} %v{d} to {s}\n", .{ serial, right_name, value.right, left_name });
        } else {
            try self.write("  %t{d}.count = select i1 true, {s} %v{d}, {s} %v{d}\n", .{
                serial,
                left_name,
                value.right,
                left_name,
                value.right,
            });
        }
        try self.write("  %v{d} = {s} {s} %v{d}, %t{d}.count\n", .{
            value.result,
            if (value.operator == .shift_left) "shl" else "lshr",
            left_name,
            value.left,
            serial,
        });
    }

    fn emitConvert(self: *FunctionEmitter, block_id: usize, value: Ir.Instruction.Convert) Error!void {
        if (!value.source.isInteger() or !value.target.isInteger()) return error.UnsupportedInstruction;
        if (value.source == value.target) return self.copyValue(value.result, value.operand);
        const serial = self.nextTemporary();
        const source_name = try llvmType(value.source);
        try self.write("  %t{d}.wide = {s} {s} %v{d} to i128\n", .{
            serial,
            if (value.source.isSignedInteger()) "sext" else "zext",
            source_name,
            value.operand,
        });
        try self.write("  %t{d}.low = icmp slt i128 %t{d}.wide, {d}\n", .{
            serial,
            serial,
            integerMinimum(value.target),
        });
        try self.write("  %t{d}.high = icmp sgt i128 %t{d}.wide, {d}\n", .{
            serial,
            serial,
            integerMaximum(value.target),
        });
        try self.write("  %t{d}.invalid = or i1 %t{d}.low, %t{d}.high\n", .{ serial, serial, serial });
        try self.write("  br i1 %t{d}.invalid, label %trap, label %b{d}.cont{d}\n", .{ serial, block_id, serial });
        try self.write("b{d}.cont{d}:\n", .{ block_id, serial });
        try self.write("  %v{d} = trunc i128 %t{d}.wide to {s}\n", .{
            value.result,
            serial,
            try llvmType(value.target),
        });
    }

    fn emitCall(self: *FunctionEmitter, value: Ir.Instruction.Call) Error!void {
        if (value.function >= self.program.functions.len) return error.InvalidProgram;
        const callee = self.program.functions[value.function];
        if (callee.parameter_types.len != value.arguments.len) return error.InvalidProgram;
        try self.output.appendSlice(self.allocator, "  ");
        if (value.result) |result| try self.write("%v{d} = ", .{result});
        try self.write("call {s} @sx_{d}(", .{ try llvmType(callee.return_type), value.function });
        for (value.arguments, 0..) |argument, index| {
            if (index != 0) try self.output.appendSlice(self.allocator, ", ");
            try self.write("{s} %v{d}", .{ try llvmType(callee.parameter_types[index]), argument });
        }
        try self.output.appendSlice(self.allocator, ")\n");
    }

    fn emitPrint(self: *FunctionEmitter, value: Ir.Instruction.Print) Error!void {
        const type_value = try self.valueType(value.value);
        const serial = self.nextTemporary();
        if (type_value == .bool) {
            try self.write("  %t{d}.text = select i1 %v{d}, ptr @.true, ptr @.false\n", .{ serial, value.value });
            try self.write("  %t{d}.print = call i32 (ptr, ...) @printf(ptr @{s}, ptr %t{d}.text)\n", .{
                serial,
                if (value.newline) ".fmt.boolean" else ".fmt.boolean.inline",
                serial,
            });
            return;
        }
        if (!type_value.isInteger()) return error.UnsupportedType;
        const type_name = try llvmType(type_value);
        if (type_value.bitWidth() < 64) {
            try self.write("  %t{d}.wide = {s} {s} %v{d} to i64\n", .{
                serial,
                if (type_value.isSignedInteger()) "sext" else "zext",
                type_name,
                value.value,
            });
        } else {
            try self.write("  %t{d}.wide = select i1 true, i64 %v{d}, i64 %v{d}\n", .{
                serial,
                value.value,
                value.value,
            });
        }
        const format = if (type_value.isSignedInteger())
            (if (value.newline) ".fmt.signed" else ".fmt.signed.inline")
        else if (value.newline) ".fmt.unsigned" else ".fmt.unsigned.inline";
        try self.write("  %t{d}.print = call i32 (ptr, ...) @printf(ptr @{s}, i64 %t{d}.wide)\n", .{
            serial,
            format,
            serial,
        });
    }

    fn emitTerminator(self: *FunctionEmitter, terminator: Ir.Terminator) Error!void {
        switch (terminator) {
            .jump => |target| try self.write("  br label %b{d}\n", .{target}),
            .branch => |branch| try self.write("  br i1 %v{d}, label %b{d}, label %b{d}\n", .{
                branch.condition,
                branch.then_block,
                branch.else_block,
            }),
            .return_value => |value| try self.write("  ret {s} %v{d}\n", .{
                try llvmType(self.function.return_type),
                value,
            }),
            .return_void => try self.output.appendSlice(self.allocator, "  ret void\n"),
            .panic => return error.UnsupportedInstruction,
        }
    }

    fn valueType(self: *FunctionEmitter, value: Ir.ValueId) Error!Ir.Type {
        if (value >= self.function.value_types.len) return error.InvalidProgram;
        return self.function.value_types[value];
    }

    fn nextTemporary(self: *FunctionEmitter) usize {
        const temporary = self.temporary;
        self.temporary += 1;
        return temporary;
    }

    fn write(self: *FunctionEmitter, comptime format: []const u8, arguments: anytype) Error!void {
        return appendFmt(self.output, self.allocator, format, arguments);
    }
};

fn llvmType(type_value: Ir.Type) Error![]const u8 {
    return switch (type_value) {
        .void => "void",
        .bool => "i1",
        .int8, .uint8 => "i8",
        .int16, .uint16 => "i16",
        .int32, .uint32 => "i32",
        .int, .uint => "i64",
        .float32 => "float",
        .float64 => "double",
        else => error.UnsupportedType,
    };
}

fn normalize(bits: u64, type_value: Ir.Type) u64 {
    const width = type_value.bitWidth();
    if (width == 64) return bits;
    return bits & ((@as(u64, 1) << @intCast(width)) - 1);
}

fn integerMinimum(type_value: Ir.Type) i128 {
    if (!type_value.isSignedInteger()) return 0;
    return -(@as(i128, 1) << @intCast(type_value.bitWidth() - 1));
}

fn integerMaximum(type_value: Ir.Type) i128 {
    return if (type_value.isSignedInteger())
        (@as(i128, 1) << @intCast(type_value.bitWidth() - 1)) - 1
    else
        (@as(i128, 1) << @intCast(type_value.bitWidth())) - 1;
}

fn appendFmt(
    output: *std.ArrayList(u8),
    allocator: Allocator,
    comptime format: []const u8,
    arguments: anytype,
) Allocator.Error!void {
    try output.appendSlice(allocator, try std.fmt.allocPrint(allocator, format, arguments));
}

test "LLVM emitter preserves checked integer operations" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var frontend = Silex.Frontend.init(allocator);
    const compilation = try frontend.compile(
        \\func calculate(left:int, right:int) int { return left * 3 + right }
        \\func main() { print(calculate(12, 8)) }
    );
    const text = try emit(allocator, compilation.ir);
    try std.testing.expect(std.mem.containsAtLeast(u8, text, 1, "llvm.smul.with.overflow.i64"));
    try std.testing.expect(std.mem.containsAtLeast(u8, text, 1, "define i32 @main()"));
}

test "LLVM emitter supports scalar floating-point loops and comparisons" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const allocator = arena.allocator();
    var frontend = Silex.Frontend.init(allocator);
    const compilation = try frontend.compile(
        \\func step(value:float) float { return value * 0.5 + 0.25 }
        \\func main() { print(step(1.0) > 0.0) }
    );
    const text = try emit(allocator, compilation.ir);
    try std.testing.expect(std.mem.containsAtLeast(u8, text, 1, "fmul float"));
    try std.testing.expect(std.mem.containsAtLeast(u8, text, 1, "fadd float"));
    try std.testing.expect(std.mem.containsAtLeast(u8, text, 1, "fcmp ogt float"));
}
