#!/usr/bin/env python3
"""Generate compact Unicode 16 tables for portable package-path admission."""

from pathlib import Path
import argparse
import unicodedata

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
UNICODE_VERSION = "16.0.0"


def u21(value: int) -> str:
    return "".join(ALPHABET[(value >> shift) & 63] for shift in (18, 12, 6, 0))


def mapping(values: dict[int, tuple[int, ...]]) -> tuple[str, str, str]:
    keys: list[str] = []
    metadata: list[str] = []
    payload: list[str] = []
    offset = 0
    for codepoint, mapped in sorted(values.items()):
        if len(mapped) > 63:
            raise ValueError(f"mapping too long for U+{codepoint:04X}")
        keys.append(u21(codepoint))
        metadata.append(u21(offset) + ALPHABET[len(mapped)])
        payload.extend(u21(item) for item in mapped)
        offset += len(mapped)
    return "".join(keys), "".join(metadata), "".join(payload)


def ranges(values: set[int]) -> str:
    merged: list[tuple[int, int]] = []
    for value in sorted(values):
        if merged and value == merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], value)
        else:
            merged.append((value, value))
    return "".join(u21(first) + u21(last) for first, last in merged)


def scalar_values():
    for value in range(0x110000):
        if not 0xD800 <= value <= 0xDFFF:
            yield value


def generated_data() -> dict[str, str]:
    decomposition: dict[int, tuple[int, ...]] = {}
    combining: dict[int, int] = {}
    lowercase: dict[int, tuple[int, ...]] = {}
    cased: set[int] = set()
    case_ignorable: set[int] = set()

    for value in scalar_values():
        character = chr(value)
        raw = unicodedata.decomposition(character)
        if raw and not raw.startswith("<"):
            decomposition[value] = tuple(int(part, 16) for part in raw.split())
        combining_class = unicodedata.combining(character)
        if combining_class:
            combining[value] = combining_class
        lowered = character.lower()
        if lowered != character:
            lowercase[value] = tuple(ord(part) for part in lowered)

        # Python's Unicode 16 casing engine exposes the two derived properties
        # through the context-sensitive Final_Sigma rule without extra UCD files.
        if ("AΣ" + character).lower()[1] == "σ":
            cased.add(value)
        elif ("AΣ" + character + "A").lower()[1] == "σ":
            case_ignorable.add(value)

    compositions: dict[tuple[int, int], int] = {}
    for composed, parts in decomposition.items():
        if len(parts) != 2 or combining.get(parts[0], 0) != 0:
            continue
        candidate = "".join(chr(part) for part in parts)
        if unicodedata.normalize("NFC", candidate) == chr(composed):
            compositions[(parts[0], parts[1])] = composed

    decomp = mapping(decomposition)
    lower = mapping(lowercase)
    return {
        "decomposition_keys": decomp[0],
        "decomposition_metadata": decomp[1],
        "decomposition_values": decomp[2],
        "combining_keys": "".join(u21(key) for key in sorted(combining)),
        "combining_values": "".join(u21(combining[key]) for key in sorted(combining)),
        "composition_keys": "".join(u21(first) + u21(second) for first, second in sorted(compositions)),
        "composition_values": "".join(u21(compositions[key]) for key in sorted(compositions)),
        "lowercase_keys": lower[0],
        "lowercase_metadata": lower[1],
        "lowercase_values": lower[2],
        "cased_ranges": ranges(cased),
        "case_ignorable_ranges": ranges(case_ignorable),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    arguments = parser.parse_args()
    if unicodedata.unidata_version != UNICODE_VERSION:
        raise SystemExit(
            f"requires Python Unicode {UNICODE_VERSION}, found {unicodedata.unidata_version}"
        )
    values = generated_data()
    header = (
        "// Generated by Tools/GeneratePackageUnicode.py from Python's Unicode 16.0 UCD.\n"
        "// Do not edit by hand. Unicode data: https://www.unicode.org/license.txt\n\n"
        f'pub const version = "{UNICODE_VERSION}";\n'
    )
    body = "".join(f'pub const {name} = "{value}";\n' for name, value in values.items())
    arguments.output.write_text(header + body, encoding="utf-8")


if __name__ == "__main__":
    main()
