pub const Symbol = enum {
    virtual_alloc,
    virtual_free,
    process_prng,
    query_performance_counter,
    query_performance_frequency,
    get_system_time_as_file_time,
    crt_write,
    crt_read,
    crt_isatty,
    crt_wopen,
    crt_close,
    crt_commit,
    crt_lseeki64,
    crt_chsize_s,
    crt_p_argc,
    crt_p_wargv,
    get_std_handle,
    get_console_screen_buffer_info,
    get_console_mode,
    set_console_mode,
    get_console_cp,
    set_console_cp,
    wait_for_single_object,
    get_current_directory_w,
    set_current_directory_w,
    get_module_file_name_w,
    get_current_process_id,
    get_environment_variable_w,
    set_environment_variable_w,
    get_environment_strings_w,
    free_environment_strings_w,
    get_file_attributes_ex_w,
    find_first_file_w,
    find_next_file_w,
    find_close,
    create_directory_w,
    delete_file_w,
    remove_directory_w,
    move_file_ex_w,
    copy_file_w,
    set_file_attributes_w,
    get_full_path_name_w,
    get_addr_info_w,
    free_addr_info_w,
    wsa_startup,
    wsa_cleanup,
    wsa_socket,
    wsa_connect,
    wsa_bind,
    wsa_listen,
    wsa_accept,
    wsa_recv,
    wsa_send,
    wsa_shutdown,
    wsa_close_socket,
    wsa_getsockname,
    wsa_getpeername,
    wsa_setsockopt,
    wsa_sendto,
    wsa_recvfrom,
    create_pipe,
    set_handle_information,
    create_process_w,
    read_file,
    write_file,
    peek_named_pipe,
    close_handle,
    terminate_process,
    get_exit_code_process,
    get_last_error,
    create_thread,
    initialize_critical_section,
    enter_critical_section,
    leave_critical_section,

    pub fn sourceName(self: Symbol) []const u8 {
        return switch (self) {
            .virtual_alloc => "VirtualAlloc",
            .virtual_free => "VirtualFree",
            .process_prng => "ProcessPrng",
            .query_performance_counter => "QueryPerformanceCounter",
            .query_performance_frequency => "QueryPerformanceFrequency",
            .get_system_time_as_file_time => "GetSystemTimeAsFileTime",
            .crt_write => "_write",
            .crt_read => "_read",
            .crt_isatty => "_isatty",
            .crt_wopen => "_wopen",
            .crt_close => "_close",
            .crt_commit => "_commit",
            .crt_lseeki64 => "_lseeki64",
            .crt_chsize_s => "_chsize_s",
            .crt_p_argc => "__p___argc",
            .crt_p_wargv => "__p___wargv",
            .get_std_handle => "GetStdHandle",
            .get_console_screen_buffer_info => "GetConsoleScreenBufferInfo",
            .get_console_mode => "GetConsoleMode",
            .set_console_mode => "SetConsoleMode",
            .get_console_cp => "GetConsoleCP",
            .set_console_cp => "SetConsoleCP",
            .wait_for_single_object => "WaitForSingleObject",
            .get_current_directory_w => "GetCurrentDirectoryW",
            .set_current_directory_w => "SetCurrentDirectoryW",
            .get_module_file_name_w => "GetModuleFileNameW",
            .get_current_process_id => "GetCurrentProcessId",
            .get_environment_variable_w => "GetEnvironmentVariableW",
            .set_environment_variable_w => "SetEnvironmentVariableW",
            .get_environment_strings_w => "GetEnvironmentStringsW",
            .free_environment_strings_w => "FreeEnvironmentStringsW",
            .get_file_attributes_ex_w => "GetFileAttributesExW",
            .find_first_file_w => "FindFirstFileW",
            .find_next_file_w => "FindNextFileW",
            .find_close => "FindClose",
            .create_directory_w => "CreateDirectoryW",
            .delete_file_w => "DeleteFileW",
            .remove_directory_w => "RemoveDirectoryW",
            .move_file_ex_w => "MoveFileExW",
            .copy_file_w => "CopyFileW",
            .set_file_attributes_w => "SetFileAttributesW",
            .get_full_path_name_w => "GetFullPathNameW",
            .get_addr_info_w => "GetAddrInfoW",
            .free_addr_info_w => "FreeAddrInfoW",
            .wsa_startup => "WSAStartup",
            .wsa_cleanup => "WSACleanup",
            .wsa_socket => "socket",
            .wsa_connect => "connect",
            .wsa_bind => "bind",
            .wsa_listen => "listen",
            .wsa_accept => "accept",
            .wsa_recv => "recv",
            .wsa_send => "send",
            .wsa_shutdown => "shutdown",
            .wsa_close_socket => "closesocket",
            .wsa_getsockname => "getsockname",
            .wsa_getpeername => "getpeername",
            .wsa_setsockopt => "setsockopt",
            .wsa_sendto => "sendto",
            .wsa_recvfrom => "recvfrom",
            .create_pipe => "CreatePipe",
            .set_handle_information => "SetHandleInformation",
            .create_process_w => "CreateProcessW",
            .read_file => "ReadFile",
            .write_file => "WriteFile",
            .peek_named_pipe => "PeekNamedPipe",
            .close_handle => "CloseHandle",
            .terminate_process => "TerminateProcess",
            .get_exit_code_process => "GetExitCodeProcess",
            .get_last_error => "GetLastError",
            .create_thread => "CreateThread",
            .initialize_critical_section => "InitializeCriticalSection",
            .enter_critical_section => "EnterCriticalSection",
            .leave_critical_section => "LeaveCriticalSection",
        };
    }

    pub fn libraryName(self: Symbol) []const u8 {
        return switch (self) {
            .virtual_alloc, .virtual_free => "KERNEL32.dll",
            .process_prng => "bcryptprimitives.dll",
            .query_performance_counter, .query_performance_frequency, .get_system_time_as_file_time => "KERNEL32.dll",
            .crt_write, .crt_read, .crt_isatty, .crt_wopen, .crt_close, .crt_commit, .crt_lseeki64, .crt_chsize_s, .crt_p_argc, .crt_p_wargv => "ucrtbase.dll",
            .get_std_handle, .get_console_screen_buffer_info, .get_console_mode, .set_console_mode, .get_console_cp, .set_console_cp, .wait_for_single_object, .get_current_directory_w, .set_current_directory_w, .get_module_file_name_w, .get_current_process_id => "KERNEL32.dll",
            .get_environment_variable_w, .set_environment_variable_w, .get_environment_strings_w, .free_environment_strings_w => "KERNEL32.dll",
            .get_file_attributes_ex_w, .find_first_file_w, .find_next_file_w, .find_close, .create_directory_w, .delete_file_w, .remove_directory_w, .move_file_ex_w, .copy_file_w, .set_file_attributes_w, .get_full_path_name_w => "KERNEL32.dll",
            .get_addr_info_w, .free_addr_info_w, .wsa_startup, .wsa_cleanup, .wsa_socket, .wsa_connect, .wsa_bind, .wsa_listen, .wsa_accept, .wsa_recv, .wsa_send, .wsa_shutdown, .wsa_close_socket, .wsa_getsockname, .wsa_getpeername, .wsa_setsockopt, .wsa_sendto, .wsa_recvfrom => "ws2_32.dll",
            .create_pipe, .set_handle_information, .create_process_w, .read_file, .write_file, .peek_named_pipe, .close_handle, .terminate_process, .get_exit_code_process, .get_last_error, .create_thread, .initialize_critical_section, .enter_critical_section, .leave_critical_section => "KERNEL32.dll",
        };
    }
};

pub const X64Site = struct {
    displacement_offset: u32,
    symbol: Symbol,
};

pub const Arm64Site = struct {
    instruction_offset: u32,
    symbol: Symbol,
};
